# The Drop — taxonomy source of truth.
# Format: ("Leaf Label", "lanes", ["synonym", ...])
# lanes: L=local, M=maker, D=digital. "LM" = both.

L, M, D, LM, LD, MD, LMD = "L", "M", "D", "LM", "LD", "MD", "LMD"

TAXONOMY = {

"Food & Drink": [
 ("Tacos", L, ["taqueria","mexican street food","burritos"]),
 ("Mexican", L, ["tex-mex","cantina","enchiladas"]),
 ("Pizza", L, ["pizzeria","slice","neapolitan"]),
 ("Burgers", L, ["cheeseburger","smash burger","patty"]),
 ("Wings", L, ["chicken wings","buffalo wings","hot wings"]),
 ("BBQ", L, ["barbecue","smokehouse","brisket","ribs"]),
 ("Sandwiches & Subs", L, ["deli","hoagie","sub shop","panini"]),
 ("Sushi", L, ["japanese","sashimi","nigiri","poke"]),
 ("Ramen & Noodles", L, ["pho","udon","noodle bar"]),
 ("Chinese", L, ["szechuan","dim sum","cantonese"]),
 ("Thai", L, ["pad thai","curry house"]),
 ("Indian", L, ["curry","tandoori","masala"]),
 ("Korean", L, ["kbbq","korean bbq","bibimbap"]),
 ("Vietnamese", L, ["banh mi","pho"]),
 ("Mediterranean", L, ["greek","gyro","falafel","shawarma"]),
 ("Middle Eastern", L, ["halal","kebab","hummus"]),
 ("Italian", L, ["pasta","trattoria","ristorante"]),
 ("Steakhouse", L, ["steak","prime rib","chophouse"]),
 ("Seafood", L, ["fish","oysters","crab","lobster"]),
 ("Soul Food", L, ["southern","fried chicken","comfort food"]),
 ("Latin American", L, ["peruvian","colombian","cuban","arepas"]),
 ("Brazilian", L, ["churrascaria","rodizio"]),
 ("Breakfast & Brunch", L, ["diner","pancakes","eggs","waffles"]),
 ("Salads & Bowls", L, ["healthy","grain bowl","poke bowl"]),
 ("Vegan & Vegetarian", L, ["plant based","meatless"]),
 ("Food Truck", L, ["mobile food","street food","truck"]),
 ("Hot Dogs", L, ["franks","brats","sausage"]),
 ("Fried Chicken", L, ["chicken tenders","nashville hot"]),
 ("Buffet", L, ["all you can eat","aycE"]),
 ("Catering", L, ["party trays","event food","office lunch"]),
 ("Meal Prep", L, ["meal kits","prepared meals","weekly meals"]),
],

"Coffee & Bakery": [
 ("Pretzels & Bagels", L, ["bagel shop","soft pretzel"]),
 ("Pies & Tarts", LM, ["pie shop","hand pies"]),
 ("Macarons & Fine Pastry", LM, ["macaron","french pastry","eclair"]),
 ("Gluten Free Bakery", LM, ["celiac","gf baked goods"]),
 ("Coffee Shop", L, ["cafe","espresso","latte","coffee house"]),
 ("Specialty Roaster", LM, ["roastery","single origin","beans"]),
 ("Tea House", LM, ["boba","bubble tea","matcha","chai"]),
 ("Bakery", LM, ["pastry","croissant","bread","patisserie"]),
 ("Donuts", L, ["doughnuts","cruller"]),
 ("Cupcakes & Cakes", LM, ["custom cake","birthday cake","cake shop"]),
 ("Cookies & Brownies", LM, ["cookie shop","edible cookie dough"]),
 ("Ice Cream & Frozen", L, ["gelato","frozen yogurt","soft serve","froyo"]),
 ("Shaved Ice & Snow Cones", L, ["hawaiian ice","italian ice"]),
 ("Smoothies & Juice", L, ["juice bar","acai","protein shake"]),
 ("Candy & Chocolate", LM, ["chocolatier","sweets","confectionery","fudge"]),
 ("Crepes & Waffles", L, ["dessert cafe"]),
],

"Bars & Nightlife": [
 ("Rooftop & Patio Bar", L, ["rooftop","outdoor bar","patio"]),
 ("Wine & Paint Night", L, ["sip and paint","paint and sip"]),
 ("Trivia & Game Night", L, ["pub trivia","bar games"]),
 ("Country & Line Dancing", L, ["honky tonk","two step","line dance"]),
 ("Cocktail Bar", L, ["mixology","craft cocktails","speakeasy"]),
 ("Sports Bar", L, ["game day","pub","sports pub"]),
 ("Brewery & Taproom", L, ["craft beer","brewpub","beer garden"]),
 ("Distillery", LM, ["spirits","whiskey","tasting room"]),
 ("Winery & Wine Bar", LM, ["vineyard","wine tasting","enoteca"]),
 ("Cidery", LM, ["hard cider","cider house"]),
 ("Dive Bar", L, ["neighborhood bar","local bar"]),
 ("Nightclub", L, ["club","dancing","dj night"]),
 ("Karaoke", L, ["sing","karaoke bar"]),
 ("Hookah Lounge", L, ["shisha","hookah bar"]),
 ("Comedy Club", L, ["stand up","open mic comedy"]),
 ("Live Music Venue", L, ["concert venue","music hall","gig"]),
 ("Mocktail & Zero Proof", L, ["non alcoholic","sober bar","na drinks"]),
],

"Grocery & Specialty Food": [
 ("Bakery Wholesale & Bulk", LM, ["bulk order","wholesale food"]),
 ("Coffee Subscription", MD, ["bean subscription","coffee club"]),
 ("Meat & Seafood Boxes", LM, ["meat box","bulk meat","freezer pack"]),
 ("Olive Oil & Vinegar", M, ["evoo","balsamic","infused oil"]),
 ("Butcher", LM, ["meat market","meat shop"]),
 ("Fishmonger", L, ["seafood market","fish market"]),
 ("Cheese Shop", LM, ["creamery","fromagerie"]),
 ("Farmers Market Vendor", LM, ["farm stand","market stall","produce stand"]),
 ("CSA & Produce Box", L, ["farm share","veggie box","produce delivery"]),
 ("Hot Sauce & Condiments", M, ["salsa","bbq sauce","seasoning"]),
 ("Jams & Preserves", M, ["jelly","canning","pickles"]),
 ("Honey & Syrups", M, ["raw honey","maple syrup","apiary"]),
 ("Spices & Seasonings", M, ["rubs","spice blend","seasoning"]),
 ("Granola & Snacks", M, ["trail mix","jerky","protein bar"]),
 ("International Market", L, ["asian market","latin market","ethnic grocery"]),
 ("Health Food Store", L, ["natural foods","organic grocery","supplements"]),
 ("Liquor & Bottle Shop", L, ["package store","wine shop","beer store"]),
],

"Auto": [
 ("Oil Change", L, ["lube","quick lube","oil service"]),
 ("Tires", L, ["tire shop","new tires","tire rotation"]),
 ("Brakes", L, ["brake service","brake pads","rotors"]),
 ("General Auto Repair", L, ["mechanic","auto shop","car repair","garage"]),
 ("Transmission", L, ["transmission repair","gearbox"]),
 ("Engine & Diagnostics", L, ["check engine","engine repair","tune up"]),
 ("Car Wash", L, ["wash","exterior wash","drive through wash"]),
 ("Auto Detailing", L, ["detail","car detail","interior detail","ceramic coating"]),
 ("Window Tint", LM, ["tinting","auto tint","ceramic tint"]),
 ("Paint Protection Film", LM, ["ppf","clear bra","paint protection"]),
 ("Vinyl Wrap", LM, ["car wrap","vehicle wrap","color change wrap"]),
 ("Body Shop & Collision", L, ["dent repair","collision repair","auto body"]),
 ("Paintless Dent Repair", L, ["pdr","dent removal","hail damage"]),
 ("Windshield & Glass", L, ["auto glass","chip repair","windshield replacement"]),
 ("Alignment & Suspension", L, ["wheel alignment","struts","shocks"]),
 ("Exhaust & Muffler", L, ["muffler shop","catback","exhaust repair"]),
 ("Auto Electrical", L, ["battery","alternator","starter","wiring"]),
 ("AC & Heating Service", L, ["auto ac","recharge","climate control"]),
 ("Performance & Tuning", L, ["tuning","dyno","aftermarket","ecu tune"]),
 ("Auto Upholstery", LM, ["seat repair","headliner","custom interior"]),
 ("Motorcycle Service", L, ["moto repair","bike shop","powersports"]),
 ("RV & Trailer Service", L, ["rv repair","camper service","trailer repair"]),
 ("Boat & Marine Service", L, ["marine repair","boat detail","outboard"]),
 ("Fleet & Commercial", L, ["fleet service","commercial vehicle","truck repair"]),
 ("Roadside & Towing", L, ["tow","jump start","lockout"]),
 ("Car Rental", L, ["rental car","van rental","truck rental"]),
],

"Home Services": [
 ("House Cleaning", L, ["maid service","housekeeping","deep clean"]),
 ("Window Washing", L, ["window cleaning","glass cleaning"]),
 ("Carpet Cleaning", L, ["rug cleaning","steam clean","upholstery cleaning"]),
 ("Pressure Washing", L, ["power washing","driveway cleaning","soft wash"]),
 ("Gutter Cleaning", L, ["gutters","downspout","gutter guard"]),
 ("Air Duct Cleaning", L, ["duct cleaning","vent cleaning","dryer vent"]),
 ("Chimney Sweep", L, ["chimney cleaning","flue"]),
 ("Pest Control", L, ["exterminator","bug spray","termite","rodent"]),
 ("Junk Removal", L, ["hauling","debris removal","dumpster"]),
 ("Moving & Packing", L, ["movers","moving company","local move"]),
 ("Handyman", L, ["home repair","odd jobs","fix it"]),
 ("Appliance Repair", L, ["washer repair","fridge repair","dryer repair"]),
 ("HVAC Service", L, ["furnace","ac repair","heating and cooling","tune up"]),
 ("Plumbing", L, ["plumber","drain cleaning","water heater","leak"]),
 ("Electrical", L, ["electrician","panel upgrade","wiring","outlets"]),
 ("Locksmith", L, ["lock change","rekey","key cutting"]),
 ("Home Organizing", L, ["closet organizer","decluttering","professional organizer"]),
 ("Snow Removal", L, ["plowing","snow shoveling","ice removal"]),
 ("Home Security", L, ["alarm system","cameras","doorbell camera"]),
 ("Smart Home Setup", L, ["home automation","wifi setup","av install"]),
 ("Septic & Sewer", L, ["septic pumping","sewer line","drain line"]),
 ("Water Treatment", L, ["water softener","filtration","reverse osmosis"]),
],

"Home Improvement": [
 ("Interior Painting", L, ["painter","wall painting","repaint"]),
 ("Exterior Painting", L, ["house painting","siding paint"]),
 ("Flooring Install", L, ["hardwood","lvp","tile floor","carpet install"]),
 ("Tile & Stone", L, ["backsplash","tile work","stonework"]),
 ("Cabinets", LM, ["cabinetry","kitchen cabinets","refacing"]),
 ("Countertops", LM, ["granite","quartz","butcher block","epoxy counter"]),
 ("Kitchen Remodel", L, ["kitchen renovation","kitchen redo"]),
 ("Bathroom Remodel", L, ["bath renovation","shower remodel"]),
 ("Basement Finishing", L, ["basement remodel","basement build out"]),
 ("Drywall & Texture", L, ["sheetrock","patching","mudding"]),
 ("Trim & Millwork", LM, ["baseboard","crown molding","wainscoting"]),
 ("Doors & Windows", L, ["window replacement","door install","entry door"]),
 ("Roofing", L, ["roof repair","reroof","shingles"]),
 ("Siding", L, ["vinyl siding","stucco","fiber cement"]),
 ("Insulation", L, ["attic insulation","spray foam","weatherization"]),
 ("Garage & Epoxy Floors", L, ["garage floor","epoxy coating","garage door"]),
 ("Concrete & Masonry", L, ["driveway","patio concrete","brickwork","retaining wall"]),
 ("Fencing", L, ["fence install","privacy fence","gate"]),
 ("Decks & Patios", L, ["deck build","pergola","covered patio"]),
 ("Solar", L, ["solar panels","pv install","solar quote"]),
],

"Outdoor & Yard": [
 ("Sod & Turf", L, ["new lawn","artificial turf","sod install"]),
 ("Mosquito & Tick Control", L, ["yard spray","mosquito treatment"]),
 ("Greenhouse & Garden Build", L, ["raised beds","greenhouse","garden install"]),
 ("Pond & Water Features", L, ["fountain","koi pond","waterfall"]),
 ("Outdoor Kitchens & Fire", L, ["fire pit","outdoor grill","bbq island"]),
 ("Playsets & Trampolines", L, ["swing set","playground install","trampoline"]),
 ("Lawn Care", L, ["mowing","lawn mowing","yard service"]),
 ("Landscaping", L, ["landscape design","hardscape","yard makeover"]),
 ("Tree Service", L, ["tree trimming","tree removal","arborist","stump grinding"]),
 ("Sprinklers & Irrigation", L, ["sprinkler repair","irrigation system","blowout"]),
 ("Weed & Fertilizer", L, ["weed control","lawn treatment","aeration"]),
 ("Garden Center & Nursery", L, ["plants","nursery","garden supply"]),
 ("Pool & Spa Service", L, ["pool cleaning","hot tub service","pool opening"]),
 ("Outdoor Lighting", L, ["landscape lighting","holiday lights","string lights"]),
 ("Holiday Light Install", L, ["christmas lights","light hanging"]),
 ("Firewood & Fuel", L, ["cord wood","propane","pellet"]),
],

"Personal Care": [
 ("Barber", L, ["haircut","fade","mens cut","barbershop"]),
 ("Hair Salon", L, ["stylist","womens cut","blowout"]),
 ("Hair Color", L, ["balayage","highlights","dye"]),
 ("Hair Extensions", L, ["weave","tape ins","wigs"]),
 ("Nails", L, ["manicure","pedicure","gel nails","acrylics","nail salon"]),
 ("Lashes", L, ["eyelash extensions","lash lift","lashes"]),
 ("Brows", L, ["microblading","brow lamination","threading","waxing brows"]),
 ("Waxing & Hair Removal", L, ["wax","laser hair removal","sugaring"]),
 ("Facials & Skincare", L, ["esthetician","facial","hydrafacial","chemical peel"]),
 ("Massage", L, ["deep tissue","swedish","sports massage","massage therapy"]),
 ("Day Spa", L, ["spa day","spa package","sauna"]),
 ("Tanning", L, ["spray tan","tanning salon","sunless"]),
 ("Makeup Artist", L, ["mua","bridal makeup","glam"]),
 ("Tattoo", L, ["tattoo shop","ink","tattoo artist"]),
 ("Piercing", L, ["body piercing","ear piercing"]),
 ("Permanent Makeup", L, ["pmu","lip blush","powder brows"]),
 ("Teeth Whitening", L, ["whitening","cosmetic whitening"]),
 ("Barber & Beard Care", LM, ["beard trim","hot shave","beard oil"]),
],

"Health & Wellness": [
 ("Dermatology", L, ["skin doctor","mole check","acne treatment"]),
 ("Podiatry & Foot Care", L, ["foot doctor","orthotics"]),
 ("Womens Health", L, ["obgyn","womens clinic"]),
 ("Mens Health", L, ["trt","mens clinic","hormone therapy"]),
 ("Hair Restoration", L, ["hair transplant","prp hair","thinning"]),
 ("Chiropractic", L, ["chiropractor","adjustment","spinal"]),
 ("Physical Therapy", L, ["pt","rehab","dry needling"]),
 ("Acupuncture", L, ["dry needling","tcm","cupping"]),
 ("Dental", L, ["dentist","cleaning","teeth cleaning","checkup"]),
 ("Orthodontics", L, ["braces","invisalign","aligners"]),
 ("Optometry", L, ["eye exam","glasses","contacts","optical"]),
 ("Med Spa", L, ["botox","filler","injectables","aesthetics"]),
 ("IV Therapy", L, ["iv drip","hydration therapy","vitamin drip"]),
 ("Cryotherapy & Recovery", L, ["cold plunge","cryo","compression","recovery lounge"]),
 ("Float Therapy", L, ["sensory deprivation","float tank"]),
 ("Hearing", L, ["hearing test","hearing aids","audiology"]),
 ("Weight & Nutrition Coaching", L, ["dietitian","nutritionist","meal coaching"]),
 ("Primary & Urgent Care", L, ["walk in clinic","urgent care","checkup"]),
 ("Lab & Screening", L, ["blood work","health screening","panel"]),
 ("Counseling & Therapy", LD, ["therapist","mental health","talk therapy"]),
 ("Sleep & Breathwork", LD, ["breathwork","sleep coaching","meditation session"]),
],

"Fitness": [
 ("Rowing & Erg", L, ["rowing studio","erg class"]),
 ("Stretch & Mobility", L, ["assisted stretching","mobility session"]),
 ("Pickleball & Courts", L, ["pickleball","court rental","tennis court"]),
 ("Indoor Golf League", L, ["golf league","sim league"]),
 ("Gym Membership", L, ["fitness center","health club","gym"]),
 ("Personal Training", LD, ["trainer","one on one training","pt session"]),
 ("Group Fitness", L, ["bootcamp","hiit","group class"]),
 ("CrossFit", L, ["box","wod","functional fitness"]),
 ("Yoga", LD, ["hot yoga","vinyasa","yoga class"]),
 ("Pilates", L, ["reformer","mat pilates"]),
 ("Barre", L, ["barre class"]),
 ("Spin & Cycling Studio", L, ["spin class","indoor cycling"]),
 ("Boxing & Kickboxing", L, ["boxing gym","muay thai","kickboxing"]),
 ("Martial Arts", L, ["bjj","jiu jitsu","karate","taekwondo","mma"]),
 ("Climbing Gym", L, ["bouldering","rock climbing","climbing"]),
 ("Swim & Aquatics", L, ["swim lessons","lap swim","pool"]),
 ("Dance Fitness", L, ["zumba","dance cardio"]),
 ("Run Club & Training", L, ["running group","marathon training"]),
 ("Golf Simulator & Range", L, ["driving range","golf sim","launch monitor"]),
],

"Entertainment": [
 ("Movie Theater", L, ["cinema","movies","film"]),
 ("Bowling", L, ["bowling alley","lanes"]),
 ("Arcade", L, ["barcade","game arcade","pinball"]),
 ("Escape Room", L, ["escape game","puzzle room"]),
 ("Axe Throwing", L, ["hatchet throwing","axe bar"]),
 ("Mini Golf", L, ["putt putt","miniature golf"]),
 ("Go Karts", L, ["karting","racing track"]),
 ("Laser Tag", L, ["lasertag"]),
 ("Pool & Billiards", L, ["pool hall","billiards","snooker"]),
 ("VR Experience", L, ["virtual reality","vr arcade"]),
 ("Theater & Performing Arts", L, ["playhouse","stage show","musical"]),
 ("Concerts & Shows", L, ["live show","tour","gig"]),
 ("Museums & Galleries", L, ["museum","art gallery","exhibit"]),
 ("Zoo & Aquarium", L, ["zoo","aquarium","wildlife park"]),
 ("Amusement & Water Park", L, ["theme park","water park","rides"]),
 ("Trampoline Park", L, ["jump park","ninja course"]),
 ("Sporting Event", L, ["game tickets","match","stadium"]),
 ("Casino & Gaming", L, ["gaming floor","casino"]),
],

"Activities & Outdoors": [
 ("Ski & Snowboard", L, ["lift ticket","ski pass","snowboarding"]),
 ("Ski & Board Tuning", L, ["wax","edge tune","binding mount"]),
 ("Snowmobile & Tours", L, ["sled tour","snowmobiling"]),
 ("Hiking & Guided Tours", L, ["guided hike","trail tour","backpacking"]),
 ("Rafting & Kayaking", L, ["whitewater","paddle","canoe"]),
 ("Paddleboard & Surf", L, ["sup","surf lesson","paddleboarding"]),
 ("Boat & Jet Ski Rental", L, ["boat rental","watercraft","wave runner"]),
 ("Fishing Charter & Guide", L, ["fly fishing","guided fishing","charter"]),
 ("Hunting & Range", L, ["shooting range","gun range","archery"]),
 ("ATV & Off Road", L, ["utv","side by side","offroad tour"]),
 ("Camping & Glamping", L, ["campsite","yurt","glamping"]),
 ("Bike Rental & Tours", L, ["e bike","mountain bike rental","bike tour"]),
 ("Horseback Riding", L, ["trail ride","equestrian","stables"]),
 ("Hot Air Balloon & Flight", L, ["scenic flight","balloon ride","discovery flight"]),
 ("Skydiving & Adventure", L, ["tandem jump","bungee","zipline"]),
 ("Gun & Archery Lessons", L, ["firearms training","ccw class","archery lesson"]),
],

"Events & Celebrations": [
 ("Officiant & Ceremony", L, ["wedding officiant","ceremony"]),
 ("Bartending Service", L, ["mobile bar","event bartender"]),
 ("Transportation & Limo", L, ["party bus","limo","shuttle"]),
 ("Corporate Events", L, ["team building","company party","offsite"]),
 ("Event Venue", L, ["reception hall","event space","banquet"]),
 ("Wedding Services", L, ["bridal","wedding planning","officiant"]),
 ("Photography", LM, ["photographer","portraits","headshots","photo session"]),
 ("Videography", LM, ["videographer","event video","film"]),
 ("DJ & Entertainment", L, ["event dj","emcee","party dj"]),
 ("Live Band", L, ["wedding band","cover band"]),
 ("Florist", LM, ["flowers","bouquet","floral arrangement"]),
 ("Balloons & Decor", LM, ["balloon garland","party decor","backdrop"]),
 ("Party Rentals", L, ["tent rental","table rental","chair rental","bounce house"]),
 ("Photo Booth", L, ["360 booth","photobooth"]),
 ("Invitations & Stationery", M, ["wedding invites","custom cards","calligraphy"]),
 ("Cake & Dessert Table", LM, ["wedding cake","dessert bar"]),
 ("Event Catering", L, ["catering","buffet service","food service"]),
 ("Fireworks & Effects", L, ["pyro","cold sparks","sparklers"]),
],

"Retail — Apparel": [
 ("Womens Clothing", LM, ["womenswear","dresses","boutique"]),
 ("Mens Clothing", LM, ["menswear","shirts","suits"]),
 ("Streetwear", LM, ["hypebeast","street style","graphic tees"]),
 ("Vintage & Thrift", L, ["secondhand","consignment","thrift store"]),
 ("Denim", LM, ["jeans","selvedge"]),
 ("Activewear", LM, ["athleisure","workout clothes","leggings"]),
 ("Swimwear", LM, ["swimsuits","bikini","board shorts"]),
 ("Outerwear", LM, ["jackets","coats","parka"]),
 ("Footwear", LM, ["shoes","sneakers","boots"]),
 ("Sneakers & Collectibles", LM, ["kicks","hype sneakers","grails"]),
 ("Western & Workwear", LM, ["boots","cowboy","carhartt style","ranch wear"]),
 ("Hats & Headwear", LM, ["caps","beanies","snapback","custom hats"]),
 ("Custom Apparel & Embroidery", LM, ["screen printing","embroidery","custom shirts","team gear"]),
 ("Kids Clothing", LM, ["childrens clothes","baby clothes"]),
 ("Formal & Bridal Wear", L, ["tuxedo","wedding dress","gown"]),
 ("Uniforms & Team Kits", LM, ["team uniforms","work uniforms","jerseys"]),
 ("Tailoring & Alterations", L, ["seamstress","hemming","suit alterations"]),
],

"Retail — Home & Lifestyle": [
 ("Furniture", LM, ["couches","tables","home furniture"]),
 ("Custom Woodwork", M, ["woodworking","live edge","joinery","custom table"]),
 ("Home Decor", LM, ["decor","wall art","accents"]),
 ("Rugs & Textiles", LM, ["area rug","throw","blanket"]),
 ("Bedding & Linens", LM, ["sheets","duvet","pillows"]),
 ("Kitchenware", LM, ["cookware","knives","cutting board"]),
 ("Ceramics & Pottery", M, ["handmade mugs","stoneware","pottery"]),
 ("Glassware & Blown Glass", M, ["glassblowing","hand blown"]),
 ("Candles", M, ["soy candles","scented candles","wax melts"]),
 ("Soap & Bath", M, ["handmade soap","bath bombs","body butter"]),
 ("Skincare & Beauty Products", LM, ["serum","moisturizer","cosmetics"]),
 ("Fragrance", LM, ["perfume","cologne","scent"]),
 ("Plants & Planters", LM, ["houseplants","succulents","pots"]),
 ("Lighting & Lamps", LM, ["lamps","fixtures","neon signs"]),
 ("Metalwork & Forged", M, ["blacksmith","forged","metal art","knifemaking"]),
 ("Leather Goods", M, ["wallets","belts","leather bags","tooled leather"]),
 ("Stationery & Paper", M, ["notebooks","journals","prints"]),
 ("Art & Prints", M, ["original art","fine art print","poster"]),
],

"Jewelry & Accessories": [
 ("Custom Engraving", LM, ["engraving","laser engraving","personalized"]),
 ("Body Jewelry", LM, ["piercing jewelry","gauges"]),
 ("Mens Accessories", LM, ["cufflinks","tie bar","money clip"]),
 ("Hair Accessories", LM, ["scrunchies","clips","headbands"]),
 ("Fine Jewelry", LM, ["diamonds","gold","engagement ring"]),
 ("Handmade Jewelry", M, ["artisan jewelry","beaded","wire wrap"]),
 ("Silver & Turquoise", LM, ["southwest jewelry","native style","sterling"]),
 ("Watches", LM, ["timepiece","watch shop"]),
 ("Watch Repair", L, ["watch service","battery replacement","band sizing"]),
 ("Jewelry Repair & Custom", L, ["ring sizing","custom ring","resetting"]),
 ("Engagement & Bridal", LM, ["wedding bands","engagement","bridal set"]),
 ("Bags & Purses", LM, ["handbag","tote","backpack"]),
 ("Sunglasses & Eyewear", LM, ["shades","frames"]),
 ("Belts & Small Leather", M, ["wallet","card holder","keychain"]),
 ("Pins, Patches & Enamel", M, ["enamel pin","patches","stickers"]),
],

"Retail — Gear & Hobby": [
 ("Outdoor Gear", LM, ["camping gear","backpacking gear","hiking gear"]),
 ("Ski & Snowboard Shop", LM, ["snow gear","boards","skis"]),
 ("Bike Shop", L, ["bicycle","bike repair","cycling"]),
 ("Fishing & Tackle", LM, ["fly shop","tackle","lures","rods"]),
 ("Hunting & Shooting", LM, ["firearms","ammo","optics","archery"]),
 ("Water Sports Gear", LM, ["wakeboard","kayak","paddleboard"]),
 ("Golf Shop & Fitting", L, ["club fitting","golf clubs","pro shop"]),
 ("Running & Shoe Fitting", L, ["gait analysis","running shoes"]),
 ("Music Instruments", LM, ["guitar shop","instrument repair","strings"]),
 ("Records & Vinyl", LM, ["record store","vinyl","lps"]),
 ("Comics & Collectibles", LM, ["comic shop","trading cards","figures"]),
 ("Trading Cards", LM, ["sports cards","tcg","pokemon cards","breaks"]),
 ("Board Games & Tabletop", LM, ["game shop","dnd","miniatures"]),
 ("Video Games", LM, ["game store","console","retro games"]),
 ("Hobby & Models", LM, ["rc cars","model kits","drones"]),
 ("Craft & Fabric Supply", LM, ["yarn","fabric store","quilting","sewing supply"]),
 ("Art Supplies", LM, ["paint","canvas","brushes"]),
 ("3D Printing & Maker Supply", MD, ["filament","resin printing","prototyping"]),
 ("Tools & Equipment", LM, ["power tools","hand tools","tool rental"]),
 ("Sporting Goods", LM, ["athletic gear","team sports","equipment"]),
],

"Kids & Family": [
 ("Kids Sports Leagues", L, ["youth sports","little league","rec league"]),
 ("Music & Theater for Kids", L, ["kids choir","youth theater","kids band"]),
 ("Kids Haircut & Spa", L, ["kids spa","princess party"]),
 ("Family Entertainment Center", L, ["fec","family fun center"]),
 ("Childcare & Daycare", L, ["day care","preschool","nursery"]),
 ("Babysitting & Nanny", L, ["sitter","nanny","date night care"]),
 ("Kids Activities", L, ["play place","indoor playground","kids gym"]),
 ("Kids Classes", L, ["gymnastics","kids dance","tumbling"]),
 ("Kids Haircuts", L, ["childrens haircut","first haircut"]),
 ("Birthday Parties", L, ["kids party","party package","party room"]),
 ("Toys & Games", LM, ["toy store","kids toys","wooden toys"]),
 ("Baby Gear", LM, ["strollers","car seats","baby essentials"]),
 ("Maternity & Newborn", LM, ["maternity photos","newborn","doula"]),
 ("Summer Camps", L, ["day camp","kids camp","sports camp"]),
 ("Tutoring", LD, ["homework help","test prep","academic tutor"]),
 ("Family Photography", LM, ["family photos","mini session"]),
],

"Pets": [
 ("Mobile Grooming", L, ["mobile groomer","grooming van"]),
 ("Pet Waste Removal", L, ["poop scooping","yard cleanup"]),
 ("Pet Memorial & Cremation", L, ["pet cremation","memorial"]),
 ("Pet Insurance & Wellness Plans", L, ["pet plan","wellness plan"]),
 ("Dog Grooming", L, ["groomer","pet grooming","dog bath"]),
 ("Pet Boarding", L, ["kennel","dog boarding","pet hotel"]),
 ("Doggy Daycare", L, ["dog daycare","pet daycare"]),
 ("Dog Training", LD, ["obedience","puppy class","k9 training"]),
 ("Dog Walking & Sitting", L, ["pet sitter","dog walker"]),
 ("Veterinary", L, ["vet","animal clinic","pet checkup"]),
 ("Pet Supplies", LM, ["pet food","pet store","treats"]),
 ("Pet Treats & Bakery", M, ["dog treats","pet bakery"]),
 ("Pet Photography", LM, ["pet portraits","dog photos"]),
 ("Aquarium & Reptile", LM, ["fish store","reptile","terrarium"]),
 ("Equine Services", L, ["farrier","horse boarding","equine"]),
 ("Custom Pet Gear", M, ["collars","leashes","pet beds"]),
],

"Professional Services": [
 ("Estate & Probate", LD, ["will","trust","estate planning"]),
 ("Immigration Services", LD, ["visa help","immigration attorney"]),
 ("Bookkeeping Cleanup", LD, ["catch up books","reconciliation"]),
 ("Drone & Aerial Services", LM, ["drone photography","aerial mapping","roof inspection"]),
 ("Accounting & Bookkeeping", LD, ["cpa","bookkeeper","quickbooks"]),
 ("Tax Preparation", LD, ["tax prep","tax filing","irs"]),
 ("Legal Services", LD, ["attorney","lawyer","consultation"]),
 ("Insurance", L, ["insurance agent","policy quote","coverage"]),
 ("Financial Planning", LD, ["advisor","retirement planning","wealth"]),
 ("Real Estate", L, ["realtor","agent","listing","home buying"]),
 ("Home Inspection", L, ["inspector","pre purchase inspection"]),
 ("Appraisal", L, ["home appraisal","valuation"]),
 ("Mortgage & Lending", L, ["loan officer","refinance","pre approval"]),
 ("Title & Escrow", L, ["closing","title company"]),
 ("Notary & Signing", L, ["notary public","mobile notary"]),
 ("Printing & Signs", LM, ["print shop","banners","business cards","vinyl signs"]),
 ("Shipping & Mailbox", L, ["packing","mailbox rental","freight"]),
 ("IT & Computer Repair", LD, ["computer repair","tech support","managed it"]),
 ("Phone & Device Repair", L, ["screen repair","iphone repair","tablet repair"]),
 ("Marketing & Design", LD, ["branding","logo design","social media management"]),
 ("Web Development", LD, ["website build","web design","ecommerce build"]),
 ("Photography — Commercial", LM, ["product photos","real estate photos","corporate headshots"]),
 ("Staffing & Recruiting", LD, ["hiring","recruiter","temp staffing"]),
 ("Translation & Interpreting", LD, ["translator","interpreter","spanish translation"]),
 ("Consulting", LD, ["business consulting","strategy","advisory"]),
 ("Coworking & Office Space", L, ["desk rental","office space","meeting room"]),
 ("Storage", L, ["self storage","storage unit"]),
 ("Security Services", L, ["guard service","event security"]),
],

"Education & Lessons": [
 ("Fitness Certification", LD, ["personal trainer cert","coaching cert"]),
 ("Real Estate & Trade Licensing", LD, ["license course","exam course"]),
 ("Firearms & Safety Course", L, ["gun safety","concealed carry class"]),
 ("First Aid & CPR", L, ["cpr class","first aid cert"]),
 ("Music Lessons", LD, ["guitar lessons","piano lessons","voice lessons"]),
 ("Art Classes", LD, ["painting class","drawing class","paint night"]),
 ("Pottery & Ceramics Class", L, ["wheel throwing","pottery class"]),
 ("Cooking Classes", LD, ["culinary class","cooking school","baking class"]),
 ("Language Classes", LD, ["spanish class","esl","language school"]),
 ("Dance Lessons", LD, ["salsa","ballroom","hip hop class"]),
 ("Driving School", L, ["drivers ed","driving lessons"]),
 ("Trade & Certification", LD, ["welding class","cdl","osha","certification"]),
 ("Photography Workshop", LD, ["photo workshop","lightroom class"]),
 ("Woodworking Class", L, ["shop class","woodshop"]),
 ("Sewing & Craft Class", LD, ["sewing lessons","quilting class","crafting workshop"]),
 ("Coding & Tech Class", LD, ["bootcamp","programming class","web dev course"]),
 ("Business & Finance Course", D, ["online course","masterclass","training"]),
 ("Test Prep", LD, ["sat prep","act prep","exam prep"]),
],

"Travel & Stays": [
 ("Glamping & Domes", L, ["dome stay","treehouse","unique stay"]),
 ("Ski-In Lodging", L, ["slopeside","ski lodging"]),
 ("Group & Retreat Venues", L, ["retreat center","group lodging"]),
 ("Pet Friendly Stays", L, ["dog friendly hotel","pet friendly"]),
 ("Long Stay & Extended", L, ["extended stay","monthly rental"]),
 ("Hotel", L, ["lodging","hotel stay","room"]),
 ("Boutique & B&B", L, ["bed and breakfast","inn","guesthouse"]),
 ("Vacation Rental", L, ["cabin","short term rental","condo"]),
 ("Resort & Lodge", L, ["ski resort","mountain lodge","spa resort"]),
 ("Campground & RV Park", L, ["rv park","campsite","hookups"]),
 ("Airport Parking & Shuttle", L, ["park and fly","shuttle service"]),
 ("Tours & Sightseeing", L, ["city tour","guided tour","excursion"]),
 ("Travel Agency", LD, ["trip planning","travel booking"]),
 ("Luggage & Travel Gear", LM, ["suitcase","travel bag","packing cubes"]),
],

"Digital & Creative": [
 ("Sample Packs & Loops", D, ["drum kit","sample pack","loops"]),
 ("Video LUTs & Effects", D, ["luts","after effects","transitions"]),
 ("Zines & Comics", MD, ["indie comic","digital zine"]),
 ("Memberships & Communities", D, ["patreon style","private community"]),
 ("Music & Audio", D, ["album","single","beats","stems"]),
 ("Podcast & Audio Series", D, ["podcast","audio show"]),
 ("Software & Apps", D, ["app","saas","plugin","tool"]),
 ("Game & Interactive", D, ["indie game","game key","mod"]),
 ("Digital Art & Assets", D, ["wallpaper","brushes","textures","3d assets"]),
 ("Templates & Presets", D, ["lightroom presets","notion template","design template"]),
 ("Fonts & Type", D, ["typeface","font family"]),
 ("Courses & Tutorials", D, ["video course","tutorial series","workshop recording"]),
 ("Ebooks & Guides", D, ["ebook","pdf guide","zine"]),
 ("Stock Media", D, ["stock photos","stock video","sound effects"]),
 ("Practitioner Sessions", D, ["1:1 session","coaching call","consultation"]),
 ("Live Workshops", D, ["virtual workshop","live class","webinar"]),
 ("Print on Demand Art", MD, ["art print","poster print"]),
],

}
