-- The Drop — taxonomy seed. Generated; edit source.py and regenerate.
-- 24 groups, one row per node. Groups are not selectable.

insert into tags (slug, label, parent_id, lanes, synonyms, selectable, sort_order) values
  ('food-and-drink', 'Food & Drink', null, '{}'::lane[], '{}'::text[], false, 1000),
  ('coffee-and-bakery', 'Coffee & Bakery', null, '{}'::lane[], '{}'::text[], false, 2000),
  ('bars-and-nightlife', 'Bars & Nightlife', null, '{}'::lane[], '{}'::text[], false, 3000),
  ('grocery-and-specialty-food', 'Grocery & Specialty Food', null, '{}'::lane[], '{}'::text[], false, 4000),
  ('auto', 'Auto', null, '{}'::lane[], '{}'::text[], false, 5000),
  ('home-services', 'Home Services', null, '{}'::lane[], '{}'::text[], false, 6000),
  ('home-improvement', 'Home Improvement', null, '{}'::lane[], '{}'::text[], false, 7000),
  ('outdoor-and-yard', 'Outdoor & Yard', null, '{}'::lane[], '{}'::text[], false, 8000),
  ('personal-care', 'Personal Care', null, '{}'::lane[], '{}'::text[], false, 9000),
  ('health-and-wellness', 'Health & Wellness', null, '{}'::lane[], '{}'::text[], false, 10000),
  ('fitness', 'Fitness', null, '{}'::lane[], '{}'::text[], false, 11000),
  ('entertainment', 'Entertainment', null, '{}'::lane[], '{}'::text[], false, 12000),
  ('activities-and-outdoors', 'Activities & Outdoors', null, '{}'::lane[], '{}'::text[], false, 13000),
  ('events-and-celebrations', 'Events & Celebrations', null, '{}'::lane[], '{}'::text[], false, 14000),
  ('retail-apparel', 'Retail — Apparel', null, '{}'::lane[], '{}'::text[], false, 15000),
  ('retail-home-and-lifestyle', 'Retail — Home & Lifestyle', null, '{}'::lane[], '{}'::text[], false, 16000),
  ('jewelry-and-accessories', 'Jewelry & Accessories', null, '{}'::lane[], '{}'::text[], false, 17000),
  ('retail-gear-and-hobby', 'Retail — Gear & Hobby', null, '{}'::lane[], '{}'::text[], false, 18000),
  ('kids-and-family', 'Kids & Family', null, '{}'::lane[], '{}'::text[], false, 19000),
  ('pets', 'Pets', null, '{}'::lane[], '{}'::text[], false, 20000),
  ('professional-services', 'Professional Services', null, '{}'::lane[], '{}'::text[], false, 21000),
  ('education-and-lessons', 'Education & Lessons', null, '{}'::lane[], '{}'::text[], false, 22000),
  ('travel-and-stays', 'Travel & Stays', null, '{}'::lane[], '{}'::text[], false, 23000),
  ('digital-and-creative', 'Digital & Creative', null, '{}'::lane[], '{}'::text[], false, 24000);

-- Food & Drink
insert into tags (slug, label, parent_id, lanes, synonyms, selectable, sort_order) values
  ('tacos', 'Tacos', (select id from tags where slug='food-and-drink'), ARRAY['local']::lane[], ARRAY['taqueria','mexican street food','burritos']::text[], true, 1001),
  ('mexican', 'Mexican', (select id from tags where slug='food-and-drink'), ARRAY['local']::lane[], ARRAY['tex-mex','cantina','enchiladas']::text[], true, 1002),
  ('pizza', 'Pizza', (select id from tags where slug='food-and-drink'), ARRAY['local']::lane[], ARRAY['pizzeria','slice','neapolitan']::text[], true, 1003),
  ('burgers', 'Burgers', (select id from tags where slug='food-and-drink'), ARRAY['local']::lane[], ARRAY['cheeseburger','smash burger','patty']::text[], true, 1004),
  ('wings', 'Wings', (select id from tags where slug='food-and-drink'), ARRAY['local']::lane[], ARRAY['chicken wings','buffalo wings','hot wings']::text[], true, 1005),
  ('bbq', 'BBQ', (select id from tags where slug='food-and-drink'), ARRAY['local']::lane[], ARRAY['barbecue','smokehouse','brisket','ribs']::text[], true, 1006),
  ('sandwiches-and-subs', 'Sandwiches & Subs', (select id from tags where slug='food-and-drink'), ARRAY['local']::lane[], ARRAY['deli','hoagie','sub shop','panini']::text[], true, 1007),
  ('sushi', 'Sushi', (select id from tags where slug='food-and-drink'), ARRAY['local']::lane[], ARRAY['japanese','sashimi','nigiri','poke']::text[], true, 1008),
  ('ramen-and-noodles', 'Ramen & Noodles', (select id from tags where slug='food-and-drink'), ARRAY['local']::lane[], ARRAY['pho','udon','noodle bar']::text[], true, 1009),
  ('chinese', 'Chinese', (select id from tags where slug='food-and-drink'), ARRAY['local']::lane[], ARRAY['szechuan','dim sum','cantonese']::text[], true, 1010),
  ('thai', 'Thai', (select id from tags where slug='food-and-drink'), ARRAY['local']::lane[], ARRAY['pad thai','curry house']::text[], true, 1011),
  ('indian', 'Indian', (select id from tags where slug='food-and-drink'), ARRAY['local']::lane[], ARRAY['curry','tandoori','masala']::text[], true, 1012),
  ('korean', 'Korean', (select id from tags where slug='food-and-drink'), ARRAY['local']::lane[], ARRAY['kbbq','korean bbq','bibimbap']::text[], true, 1013),
  ('vietnamese', 'Vietnamese', (select id from tags where slug='food-and-drink'), ARRAY['local']::lane[], ARRAY['banh mi','pho']::text[], true, 1014),
  ('mediterranean', 'Mediterranean', (select id from tags where slug='food-and-drink'), ARRAY['local']::lane[], ARRAY['greek','gyro','falafel','shawarma']::text[], true, 1015),
  ('middle-eastern', 'Middle Eastern', (select id from tags where slug='food-and-drink'), ARRAY['local']::lane[], ARRAY['halal','kebab','hummus']::text[], true, 1016),
  ('italian', 'Italian', (select id from tags where slug='food-and-drink'), ARRAY['local']::lane[], ARRAY['pasta','trattoria','ristorante']::text[], true, 1017),
  ('steakhouse', 'Steakhouse', (select id from tags where slug='food-and-drink'), ARRAY['local']::lane[], ARRAY['steak','prime rib','chophouse']::text[], true, 1018),
  ('seafood', 'Seafood', (select id from tags where slug='food-and-drink'), ARRAY['local']::lane[], ARRAY['fish','oysters','crab','lobster']::text[], true, 1019),
  ('soul-food', 'Soul Food', (select id from tags where slug='food-and-drink'), ARRAY['local']::lane[], ARRAY['southern','fried chicken','comfort food']::text[], true, 1020),
  ('latin-american', 'Latin American', (select id from tags where slug='food-and-drink'), ARRAY['local']::lane[], ARRAY['peruvian','colombian','cuban','arepas']::text[], true, 1021),
  ('brazilian', 'Brazilian', (select id from tags where slug='food-and-drink'), ARRAY['local']::lane[], ARRAY['churrascaria','rodizio']::text[], true, 1022),
  ('breakfast-and-brunch', 'Breakfast & Brunch', (select id from tags where slug='food-and-drink'), ARRAY['local']::lane[], ARRAY['diner','pancakes','eggs','waffles']::text[], true, 1023),
  ('salads-and-bowls', 'Salads & Bowls', (select id from tags where slug='food-and-drink'), ARRAY['local']::lane[], ARRAY['healthy','grain bowl','poke bowl']::text[], true, 1024),
  ('vegan-and-vegetarian', 'Vegan & Vegetarian', (select id from tags where slug='food-and-drink'), ARRAY['local']::lane[], ARRAY['plant based','meatless']::text[], true, 1025),
  ('food-truck', 'Food Truck', (select id from tags where slug='food-and-drink'), ARRAY['local']::lane[], ARRAY['mobile food','street food','truck']::text[], true, 1026),
  ('hot-dogs', 'Hot Dogs', (select id from tags where slug='food-and-drink'), ARRAY['local']::lane[], ARRAY['franks','brats','sausage']::text[], true, 1027),
  ('fried-chicken', 'Fried Chicken', (select id from tags where slug='food-and-drink'), ARRAY['local']::lane[], ARRAY['chicken tenders','nashville hot']::text[], true, 1028),
  ('buffet', 'Buffet', (select id from tags where slug='food-and-drink'), ARRAY['local']::lane[], ARRAY['all you can eat','aycE']::text[], true, 1029),
  ('catering', 'Catering', (select id from tags where slug='food-and-drink'), ARRAY['local']::lane[], ARRAY['party trays','event food','office lunch']::text[], true, 1030),
  ('meal-prep', 'Meal Prep', (select id from tags where slug='food-and-drink'), ARRAY['local']::lane[], ARRAY['meal kits','prepared meals','weekly meals']::text[], true, 1031);

-- Coffee & Bakery
insert into tags (slug, label, parent_id, lanes, synonyms, selectable, sort_order) values
  ('pretzels-and-bagels', 'Pretzels & Bagels', (select id from tags where slug='coffee-and-bakery'), ARRAY['local']::lane[], ARRAY['bagel shop','soft pretzel']::text[], true, 2001),
  ('pies-and-tarts', 'Pies & Tarts', (select id from tags where slug='coffee-and-bakery'), ARRAY['local','maker']::lane[], ARRAY['pie shop','hand pies']::text[], true, 2002),
  ('macarons-and-fine-pastry', 'Macarons & Fine Pastry', (select id from tags where slug='coffee-and-bakery'), ARRAY['local','maker']::lane[], ARRAY['macaron','french pastry','eclair']::text[], true, 2003),
  ('gluten-free-bakery', 'Gluten Free Bakery', (select id from tags where slug='coffee-and-bakery'), ARRAY['local','maker']::lane[], ARRAY['celiac','gf baked goods']::text[], true, 2004),
  ('coffee-shop', 'Coffee Shop', (select id from tags where slug='coffee-and-bakery'), ARRAY['local']::lane[], ARRAY['cafe','espresso','latte','coffee house']::text[], true, 2005),
  ('specialty-roaster', 'Specialty Roaster', (select id from tags where slug='coffee-and-bakery'), ARRAY['local','maker']::lane[], ARRAY['roastery','single origin','beans']::text[], true, 2006),
  ('tea-house', 'Tea House', (select id from tags where slug='coffee-and-bakery'), ARRAY['local','maker']::lane[], ARRAY['boba','bubble tea','matcha','chai']::text[], true, 2007),
  ('bakery', 'Bakery', (select id from tags where slug='coffee-and-bakery'), ARRAY['local','maker']::lane[], ARRAY['pastry','croissant','bread','patisserie']::text[], true, 2008),
  ('donuts', 'Donuts', (select id from tags where slug='coffee-and-bakery'), ARRAY['local']::lane[], ARRAY['doughnuts','cruller']::text[], true, 2009),
  ('cupcakes-and-cakes', 'Cupcakes & Cakes', (select id from tags where slug='coffee-and-bakery'), ARRAY['local','maker']::lane[], ARRAY['custom cake','birthday cake','cake shop']::text[], true, 2010),
  ('cookies-and-brownies', 'Cookies & Brownies', (select id from tags where slug='coffee-and-bakery'), ARRAY['local','maker']::lane[], ARRAY['cookie shop','edible cookie dough']::text[], true, 2011),
  ('ice-cream-and-frozen', 'Ice Cream & Frozen', (select id from tags where slug='coffee-and-bakery'), ARRAY['local']::lane[], ARRAY['gelato','frozen yogurt','soft serve','froyo']::text[], true, 2012),
  ('shaved-ice-and-snow-cones', 'Shaved Ice & Snow Cones', (select id from tags where slug='coffee-and-bakery'), ARRAY['local']::lane[], ARRAY['hawaiian ice','italian ice']::text[], true, 2013),
  ('smoothies-and-juice', 'Smoothies & Juice', (select id from tags where slug='coffee-and-bakery'), ARRAY['local']::lane[], ARRAY['juice bar','acai','protein shake']::text[], true, 2014),
  ('candy-and-chocolate', 'Candy & Chocolate', (select id from tags where slug='coffee-and-bakery'), ARRAY['local','maker']::lane[], ARRAY['chocolatier','sweets','confectionery','fudge']::text[], true, 2015),
  ('crepes-and-waffles', 'Crepes & Waffles', (select id from tags where slug='coffee-and-bakery'), ARRAY['local']::lane[], ARRAY['dessert cafe']::text[], true, 2016);

-- Bars & Nightlife
insert into tags (slug, label, parent_id, lanes, synonyms, selectable, sort_order) values
  ('rooftop-and-patio-bar', 'Rooftop & Patio Bar', (select id from tags where slug='bars-and-nightlife'), ARRAY['local']::lane[], ARRAY['rooftop','outdoor bar','patio']::text[], true, 3001),
  ('wine-and-paint-night', 'Wine & Paint Night', (select id from tags where slug='bars-and-nightlife'), ARRAY['local']::lane[], ARRAY['sip and paint','paint and sip']::text[], true, 3002),
  ('trivia-and-game-night', 'Trivia & Game Night', (select id from tags where slug='bars-and-nightlife'), ARRAY['local']::lane[], ARRAY['pub trivia','bar games']::text[], true, 3003),
  ('country-and-line-dancing', 'Country & Line Dancing', (select id from tags where slug='bars-and-nightlife'), ARRAY['local']::lane[], ARRAY['honky tonk','two step','line dance']::text[], true, 3004),
  ('cocktail-bar', 'Cocktail Bar', (select id from tags where slug='bars-and-nightlife'), ARRAY['local']::lane[], ARRAY['mixology','craft cocktails','speakeasy']::text[], true, 3005),
  ('sports-bar', 'Sports Bar', (select id from tags where slug='bars-and-nightlife'), ARRAY['local']::lane[], ARRAY['game day','pub','sports pub']::text[], true, 3006),
  ('brewery-and-taproom', 'Brewery & Taproom', (select id from tags where slug='bars-and-nightlife'), ARRAY['local']::lane[], ARRAY['craft beer','brewpub','beer garden']::text[], true, 3007),
  ('distillery', 'Distillery', (select id from tags where slug='bars-and-nightlife'), ARRAY['local','maker']::lane[], ARRAY['spirits','whiskey','tasting room']::text[], true, 3008),
  ('winery-and-wine-bar', 'Winery & Wine Bar', (select id from tags where slug='bars-and-nightlife'), ARRAY['local','maker']::lane[], ARRAY['vineyard','wine tasting','enoteca']::text[], true, 3009),
  ('cidery', 'Cidery', (select id from tags where slug='bars-and-nightlife'), ARRAY['local','maker']::lane[], ARRAY['hard cider','cider house']::text[], true, 3010),
  ('dive-bar', 'Dive Bar', (select id from tags where slug='bars-and-nightlife'), ARRAY['local']::lane[], ARRAY['neighborhood bar','local bar']::text[], true, 3011),
  ('nightclub', 'Nightclub', (select id from tags where slug='bars-and-nightlife'), ARRAY['local']::lane[], ARRAY['club','dancing','dj night']::text[], true, 3012),
  ('karaoke', 'Karaoke', (select id from tags where slug='bars-and-nightlife'), ARRAY['local']::lane[], ARRAY['sing','karaoke bar']::text[], true, 3013),
  ('hookah-lounge', 'Hookah Lounge', (select id from tags where slug='bars-and-nightlife'), ARRAY['local']::lane[], ARRAY['shisha','hookah bar']::text[], true, 3014),
  ('comedy-club', 'Comedy Club', (select id from tags where slug='bars-and-nightlife'), ARRAY['local']::lane[], ARRAY['stand up','open mic comedy']::text[], true, 3015),
  ('live-music-venue', 'Live Music Venue', (select id from tags where slug='bars-and-nightlife'), ARRAY['local']::lane[], ARRAY['concert venue','music hall','gig']::text[], true, 3016),
  ('mocktail-and-zero-proof', 'Mocktail & Zero Proof', (select id from tags where slug='bars-and-nightlife'), ARRAY['local']::lane[], ARRAY['non alcoholic','sober bar','na drinks']::text[], true, 3017);

-- Grocery & Specialty Food
insert into tags (slug, label, parent_id, lanes, synonyms, selectable, sort_order) values
  ('bakery-wholesale-and-bulk', 'Bakery Wholesale & Bulk', (select id from tags where slug='grocery-and-specialty-food'), ARRAY['local','maker']::lane[], ARRAY['bulk order','wholesale food']::text[], true, 4001),
  ('coffee-subscription', 'Coffee Subscription', (select id from tags where slug='grocery-and-specialty-food'), ARRAY['maker','digital']::lane[], ARRAY['bean subscription','coffee club']::text[], true, 4002),
  ('meat-and-seafood-boxes', 'Meat & Seafood Boxes', (select id from tags where slug='grocery-and-specialty-food'), ARRAY['local','maker']::lane[], ARRAY['meat box','bulk meat','freezer pack']::text[], true, 4003),
  ('olive-oil-and-vinegar', 'Olive Oil & Vinegar', (select id from tags where slug='grocery-and-specialty-food'), ARRAY['maker']::lane[], ARRAY['evoo','balsamic','infused oil']::text[], true, 4004),
  ('butcher', 'Butcher', (select id from tags where slug='grocery-and-specialty-food'), ARRAY['local','maker']::lane[], ARRAY['meat market','meat shop']::text[], true, 4005),
  ('fishmonger', 'Fishmonger', (select id from tags where slug='grocery-and-specialty-food'), ARRAY['local']::lane[], ARRAY['seafood market','fish market']::text[], true, 4006),
  ('cheese-shop', 'Cheese Shop', (select id from tags where slug='grocery-and-specialty-food'), ARRAY['local','maker']::lane[], ARRAY['creamery','fromagerie']::text[], true, 4007),
  ('farmers-market-vendor', 'Farmers Market Vendor', (select id from tags where slug='grocery-and-specialty-food'), ARRAY['local','maker']::lane[], ARRAY['farm stand','market stall','produce stand']::text[], true, 4008),
  ('csa-and-produce-box', 'CSA & Produce Box', (select id from tags where slug='grocery-and-specialty-food'), ARRAY['local']::lane[], ARRAY['farm share','veggie box','produce delivery']::text[], true, 4009),
  ('hot-sauce-and-condiments', 'Hot Sauce & Condiments', (select id from tags where slug='grocery-and-specialty-food'), ARRAY['maker']::lane[], ARRAY['salsa','bbq sauce','seasoning']::text[], true, 4010),
  ('jams-and-preserves', 'Jams & Preserves', (select id from tags where slug='grocery-and-specialty-food'), ARRAY['maker']::lane[], ARRAY['jelly','canning','pickles']::text[], true, 4011),
  ('honey-and-syrups', 'Honey & Syrups', (select id from tags where slug='grocery-and-specialty-food'), ARRAY['maker']::lane[], ARRAY['raw honey','maple syrup','apiary']::text[], true, 4012),
  ('spices-and-seasonings', 'Spices & Seasonings', (select id from tags where slug='grocery-and-specialty-food'), ARRAY['maker']::lane[], ARRAY['rubs','spice blend','seasoning']::text[], true, 4013),
  ('granola-and-snacks', 'Granola & Snacks', (select id from tags where slug='grocery-and-specialty-food'), ARRAY['maker']::lane[], ARRAY['trail mix','jerky','protein bar']::text[], true, 4014),
  ('international-market', 'International Market', (select id from tags where slug='grocery-and-specialty-food'), ARRAY['local']::lane[], ARRAY['asian market','latin market','ethnic grocery']::text[], true, 4015),
  ('health-food-store', 'Health Food Store', (select id from tags where slug='grocery-and-specialty-food'), ARRAY['local']::lane[], ARRAY['natural foods','organic grocery','supplements']::text[], true, 4016),
  ('liquor-and-bottle-shop', 'Liquor & Bottle Shop', (select id from tags where slug='grocery-and-specialty-food'), ARRAY['local']::lane[], ARRAY['package store','wine shop','beer store']::text[], true, 4017);

-- Auto
insert into tags (slug, label, parent_id, lanes, synonyms, selectable, sort_order) values
  ('oil-change', 'Oil Change', (select id from tags where slug='auto'), ARRAY['local']::lane[], ARRAY['lube','quick lube','oil service']::text[], true, 5001),
  ('tires', 'Tires', (select id from tags where slug='auto'), ARRAY['local']::lane[], ARRAY['tire shop','new tires','tire rotation']::text[], true, 5002),
  ('brakes', 'Brakes', (select id from tags where slug='auto'), ARRAY['local']::lane[], ARRAY['brake service','brake pads','rotors']::text[], true, 5003),
  ('general-auto-repair', 'General Auto Repair', (select id from tags where slug='auto'), ARRAY['local']::lane[], ARRAY['mechanic','auto shop','car repair','garage']::text[], true, 5004),
  ('transmission', 'Transmission', (select id from tags where slug='auto'), ARRAY['local']::lane[], ARRAY['transmission repair','gearbox']::text[], true, 5005),
  ('engine-and-diagnostics', 'Engine & Diagnostics', (select id from tags where slug='auto'), ARRAY['local']::lane[], ARRAY['check engine','engine repair','tune up']::text[], true, 5006),
  ('car-wash', 'Car Wash', (select id from tags where slug='auto'), ARRAY['local']::lane[], ARRAY['wash','exterior wash','drive through wash']::text[], true, 5007),
  ('auto-detailing', 'Auto Detailing', (select id from tags where slug='auto'), ARRAY['local']::lane[], ARRAY['detail','car detail','interior detail','ceramic coating']::text[], true, 5008),
  ('window-tint', 'Window Tint', (select id from tags where slug='auto'), ARRAY['local','maker']::lane[], ARRAY['tinting','auto tint','ceramic tint']::text[], true, 5009),
  ('paint-protection-film', 'Paint Protection Film', (select id from tags where slug='auto'), ARRAY['local','maker']::lane[], ARRAY['ppf','clear bra','paint protection']::text[], true, 5010),
  ('vinyl-wrap', 'Vinyl Wrap', (select id from tags where slug='auto'), ARRAY['local','maker']::lane[], ARRAY['car wrap','vehicle wrap','color change wrap']::text[], true, 5011),
  ('body-shop-and-collision', 'Body Shop & Collision', (select id from tags where slug='auto'), ARRAY['local']::lane[], ARRAY['dent repair','collision repair','auto body']::text[], true, 5012),
  ('paintless-dent-repair', 'Paintless Dent Repair', (select id from tags where slug='auto'), ARRAY['local']::lane[], ARRAY['pdr','dent removal','hail damage']::text[], true, 5013),
  ('windshield-and-glass', 'Windshield & Glass', (select id from tags where slug='auto'), ARRAY['local']::lane[], ARRAY['auto glass','chip repair','windshield replacement']::text[], true, 5014),
  ('alignment-and-suspension', 'Alignment & Suspension', (select id from tags where slug='auto'), ARRAY['local']::lane[], ARRAY['wheel alignment','struts','shocks']::text[], true, 5015),
  ('exhaust-and-muffler', 'Exhaust & Muffler', (select id from tags where slug='auto'), ARRAY['local']::lane[], ARRAY['muffler shop','catback','exhaust repair']::text[], true, 5016),
  ('auto-electrical', 'Auto Electrical', (select id from tags where slug='auto'), ARRAY['local']::lane[], ARRAY['battery','alternator','starter','wiring']::text[], true, 5017),
  ('ac-and-heating-service', 'AC & Heating Service', (select id from tags where slug='auto'), ARRAY['local']::lane[], ARRAY['auto ac','recharge','climate control']::text[], true, 5018),
  ('performance-and-tuning', 'Performance & Tuning', (select id from tags where slug='auto'), ARRAY['local']::lane[], ARRAY['tuning','dyno','aftermarket','ecu tune']::text[], true, 5019),
  ('auto-upholstery', 'Auto Upholstery', (select id from tags where slug='auto'), ARRAY['local','maker']::lane[], ARRAY['seat repair','headliner','custom interior']::text[], true, 5020),
  ('motorcycle-service', 'Motorcycle Service', (select id from tags where slug='auto'), ARRAY['local']::lane[], ARRAY['moto repair','bike shop','powersports']::text[], true, 5021),
  ('rv-and-trailer-service', 'RV & Trailer Service', (select id from tags where slug='auto'), ARRAY['local']::lane[], ARRAY['rv repair','camper service','trailer repair']::text[], true, 5022),
  ('boat-and-marine-service', 'Boat & Marine Service', (select id from tags where slug='auto'), ARRAY['local']::lane[], ARRAY['marine repair','boat detail','outboard']::text[], true, 5023),
  ('fleet-and-commercial', 'Fleet & Commercial', (select id from tags where slug='auto'), ARRAY['local']::lane[], ARRAY['fleet service','commercial vehicle','truck repair']::text[], true, 5024),
  ('roadside-and-towing', 'Roadside & Towing', (select id from tags where slug='auto'), ARRAY['local']::lane[], ARRAY['tow','jump start','lockout']::text[], true, 5025),
  ('car-rental', 'Car Rental', (select id from tags where slug='auto'), ARRAY['local']::lane[], ARRAY['rental car','van rental','truck rental']::text[], true, 5026);

-- Home Services
insert into tags (slug, label, parent_id, lanes, synonyms, selectable, sort_order) values
  ('house-cleaning', 'House Cleaning', (select id from tags where slug='home-services'), ARRAY['local']::lane[], ARRAY['maid service','housekeeping','deep clean']::text[], true, 6001),
  ('window-washing', 'Window Washing', (select id from tags where slug='home-services'), ARRAY['local']::lane[], ARRAY['window cleaning','glass cleaning']::text[], true, 6002),
  ('carpet-cleaning', 'Carpet Cleaning', (select id from tags where slug='home-services'), ARRAY['local']::lane[], ARRAY['rug cleaning','steam clean','upholstery cleaning']::text[], true, 6003),
  ('pressure-washing', 'Pressure Washing', (select id from tags where slug='home-services'), ARRAY['local']::lane[], ARRAY['power washing','driveway cleaning','soft wash']::text[], true, 6004),
  ('gutter-cleaning', 'Gutter Cleaning', (select id from tags where slug='home-services'), ARRAY['local']::lane[], ARRAY['gutters','downspout','gutter guard']::text[], true, 6005),
  ('air-duct-cleaning', 'Air Duct Cleaning', (select id from tags where slug='home-services'), ARRAY['local']::lane[], ARRAY['duct cleaning','vent cleaning','dryer vent']::text[], true, 6006),
  ('chimney-sweep', 'Chimney Sweep', (select id from tags where slug='home-services'), ARRAY['local']::lane[], ARRAY['chimney cleaning','flue']::text[], true, 6007),
  ('pest-control', 'Pest Control', (select id from tags where slug='home-services'), ARRAY['local']::lane[], ARRAY['exterminator','bug spray','termite','rodent']::text[], true, 6008),
  ('junk-removal', 'Junk Removal', (select id from tags where slug='home-services'), ARRAY['local']::lane[], ARRAY['hauling','debris removal','dumpster']::text[], true, 6009),
  ('moving-and-packing', 'Moving & Packing', (select id from tags where slug='home-services'), ARRAY['local']::lane[], ARRAY['movers','moving company','local move']::text[], true, 6010),
  ('handyman', 'Handyman', (select id from tags where slug='home-services'), ARRAY['local']::lane[], ARRAY['home repair','odd jobs','fix it']::text[], true, 6011),
  ('appliance-repair', 'Appliance Repair', (select id from tags where slug='home-services'), ARRAY['local']::lane[], ARRAY['washer repair','fridge repair','dryer repair']::text[], true, 6012),
  ('hvac-service', 'HVAC Service', (select id from tags where slug='home-services'), ARRAY['local']::lane[], ARRAY['furnace','ac repair','heating and cooling','tune up']::text[], true, 6013),
  ('plumbing', 'Plumbing', (select id from tags where slug='home-services'), ARRAY['local']::lane[], ARRAY['plumber','drain cleaning','water heater','leak']::text[], true, 6014),
  ('electrical', 'Electrical', (select id from tags where slug='home-services'), ARRAY['local']::lane[], ARRAY['electrician','panel upgrade','wiring','outlets']::text[], true, 6015),
  ('locksmith', 'Locksmith', (select id from tags where slug='home-services'), ARRAY['local']::lane[], ARRAY['lock change','rekey','key cutting']::text[], true, 6016),
  ('home-organizing', 'Home Organizing', (select id from tags where slug='home-services'), ARRAY['local']::lane[], ARRAY['closet organizer','decluttering','professional organizer']::text[], true, 6017),
  ('snow-removal', 'Snow Removal', (select id from tags where slug='home-services'), ARRAY['local']::lane[], ARRAY['plowing','snow shoveling','ice removal']::text[], true, 6018),
  ('home-security', 'Home Security', (select id from tags where slug='home-services'), ARRAY['local']::lane[], ARRAY['alarm system','cameras','doorbell camera']::text[], true, 6019),
  ('smart-home-setup', 'Smart Home Setup', (select id from tags where slug='home-services'), ARRAY['local']::lane[], ARRAY['home automation','wifi setup','av install']::text[], true, 6020),
  ('septic-and-sewer', 'Septic & Sewer', (select id from tags where slug='home-services'), ARRAY['local']::lane[], ARRAY['septic pumping','sewer line','drain line']::text[], true, 6021),
  ('water-treatment', 'Water Treatment', (select id from tags where slug='home-services'), ARRAY['local']::lane[], ARRAY['water softener','filtration','reverse osmosis']::text[], true, 6022);

-- Home Improvement
insert into tags (slug, label, parent_id, lanes, synonyms, selectable, sort_order) values
  ('interior-painting', 'Interior Painting', (select id from tags where slug='home-improvement'), ARRAY['local']::lane[], ARRAY['painter','wall painting','repaint']::text[], true, 7001),
  ('exterior-painting', 'Exterior Painting', (select id from tags where slug='home-improvement'), ARRAY['local']::lane[], ARRAY['house painting','siding paint']::text[], true, 7002),
  ('flooring-install', 'Flooring Install', (select id from tags where slug='home-improvement'), ARRAY['local']::lane[], ARRAY['hardwood','lvp','tile floor','carpet install']::text[], true, 7003),
  ('tile-and-stone', 'Tile & Stone', (select id from tags where slug='home-improvement'), ARRAY['local']::lane[], ARRAY['backsplash','tile work','stonework']::text[], true, 7004),
  ('cabinets', 'Cabinets', (select id from tags where slug='home-improvement'), ARRAY['local','maker']::lane[], ARRAY['cabinetry','kitchen cabinets','refacing']::text[], true, 7005),
  ('countertops', 'Countertops', (select id from tags where slug='home-improvement'), ARRAY['local','maker']::lane[], ARRAY['granite','quartz','butcher block','epoxy counter']::text[], true, 7006),
  ('kitchen-remodel', 'Kitchen Remodel', (select id from tags where slug='home-improvement'), ARRAY['local']::lane[], ARRAY['kitchen renovation','kitchen redo']::text[], true, 7007),
  ('bathroom-remodel', 'Bathroom Remodel', (select id from tags where slug='home-improvement'), ARRAY['local']::lane[], ARRAY['bath renovation','shower remodel']::text[], true, 7008),
  ('basement-finishing', 'Basement Finishing', (select id from tags where slug='home-improvement'), ARRAY['local']::lane[], ARRAY['basement remodel','basement build out']::text[], true, 7009),
  ('drywall-and-texture', 'Drywall & Texture', (select id from tags where slug='home-improvement'), ARRAY['local']::lane[], ARRAY['sheetrock','patching','mudding']::text[], true, 7010),
  ('trim-and-millwork', 'Trim & Millwork', (select id from tags where slug='home-improvement'), ARRAY['local','maker']::lane[], ARRAY['baseboard','crown molding','wainscoting']::text[], true, 7011),
  ('doors-and-windows', 'Doors & Windows', (select id from tags where slug='home-improvement'), ARRAY['local']::lane[], ARRAY['window replacement','door install','entry door']::text[], true, 7012),
  ('roofing', 'Roofing', (select id from tags where slug='home-improvement'), ARRAY['local']::lane[], ARRAY['roof repair','reroof','shingles']::text[], true, 7013),
  ('siding', 'Siding', (select id from tags where slug='home-improvement'), ARRAY['local']::lane[], ARRAY['vinyl siding','stucco','fiber cement']::text[], true, 7014),
  ('insulation', 'Insulation', (select id from tags where slug='home-improvement'), ARRAY['local']::lane[], ARRAY['attic insulation','spray foam','weatherization']::text[], true, 7015),
  ('garage-and-epoxy-floors', 'Garage & Epoxy Floors', (select id from tags where slug='home-improvement'), ARRAY['local']::lane[], ARRAY['garage floor','epoxy coating','garage door']::text[], true, 7016),
  ('concrete-and-masonry', 'Concrete & Masonry', (select id from tags where slug='home-improvement'), ARRAY['local']::lane[], ARRAY['driveway','patio concrete','brickwork','retaining wall']::text[], true, 7017),
  ('fencing', 'Fencing', (select id from tags where slug='home-improvement'), ARRAY['local']::lane[], ARRAY['fence install','privacy fence','gate']::text[], true, 7018),
  ('decks-and-patios', 'Decks & Patios', (select id from tags where slug='home-improvement'), ARRAY['local']::lane[], ARRAY['deck build','pergola','covered patio']::text[], true, 7019),
  ('solar', 'Solar', (select id from tags where slug='home-improvement'), ARRAY['local']::lane[], ARRAY['solar panels','pv install','solar quote']::text[], true, 7020);

-- Outdoor & Yard
insert into tags (slug, label, parent_id, lanes, synonyms, selectable, sort_order) values
  ('sod-and-turf', 'Sod & Turf', (select id from tags where slug='outdoor-and-yard'), ARRAY['local']::lane[], ARRAY['new lawn','artificial turf','sod install']::text[], true, 8001),
  ('mosquito-and-tick-control', 'Mosquito & Tick Control', (select id from tags where slug='outdoor-and-yard'), ARRAY['local']::lane[], ARRAY['yard spray','mosquito treatment']::text[], true, 8002),
  ('greenhouse-and-garden-build', 'Greenhouse & Garden Build', (select id from tags where slug='outdoor-and-yard'), ARRAY['local']::lane[], ARRAY['raised beds','greenhouse','garden install']::text[], true, 8003),
  ('pond-and-water-features', 'Pond & Water Features', (select id from tags where slug='outdoor-and-yard'), ARRAY['local']::lane[], ARRAY['fountain','koi pond','waterfall']::text[], true, 8004),
  ('outdoor-kitchens-and-fire', 'Outdoor Kitchens & Fire', (select id from tags where slug='outdoor-and-yard'), ARRAY['local']::lane[], ARRAY['fire pit','outdoor grill','bbq island']::text[], true, 8005),
  ('playsets-and-trampolines', 'Playsets & Trampolines', (select id from tags where slug='outdoor-and-yard'), ARRAY['local']::lane[], ARRAY['swing set','playground install','trampoline']::text[], true, 8006),
  ('lawn-care', 'Lawn Care', (select id from tags where slug='outdoor-and-yard'), ARRAY['local']::lane[], ARRAY['mowing','lawn mowing','yard service']::text[], true, 8007),
  ('landscaping', 'Landscaping', (select id from tags where slug='outdoor-and-yard'), ARRAY['local']::lane[], ARRAY['landscape design','hardscape','yard makeover']::text[], true, 8008),
  ('tree-service', 'Tree Service', (select id from tags where slug='outdoor-and-yard'), ARRAY['local']::lane[], ARRAY['tree trimming','tree removal','arborist','stump grinding']::text[], true, 8009),
  ('sprinklers-and-irrigation', 'Sprinklers & Irrigation', (select id from tags where slug='outdoor-and-yard'), ARRAY['local']::lane[], ARRAY['sprinkler repair','irrigation system','blowout']::text[], true, 8010),
  ('weed-and-fertilizer', 'Weed & Fertilizer', (select id from tags where slug='outdoor-and-yard'), ARRAY['local']::lane[], ARRAY['weed control','lawn treatment','aeration']::text[], true, 8011),
  ('garden-center-and-nursery', 'Garden Center & Nursery', (select id from tags where slug='outdoor-and-yard'), ARRAY['local']::lane[], ARRAY['plants','nursery','garden supply']::text[], true, 8012),
  ('pool-and-spa-service', 'Pool & Spa Service', (select id from tags where slug='outdoor-and-yard'), ARRAY['local']::lane[], ARRAY['pool cleaning','hot tub service','pool opening']::text[], true, 8013),
  ('outdoor-lighting', 'Outdoor Lighting', (select id from tags where slug='outdoor-and-yard'), ARRAY['local']::lane[], ARRAY['landscape lighting','holiday lights','string lights']::text[], true, 8014),
  ('holiday-light-install', 'Holiday Light Install', (select id from tags where slug='outdoor-and-yard'), ARRAY['local']::lane[], ARRAY['christmas lights','light hanging']::text[], true, 8015),
  ('firewood-and-fuel', 'Firewood & Fuel', (select id from tags where slug='outdoor-and-yard'), ARRAY['local']::lane[], ARRAY['cord wood','propane','pellet']::text[], true, 8016);

-- Personal Care
insert into tags (slug, label, parent_id, lanes, synonyms, selectable, sort_order) values
  ('barber', 'Barber', (select id from tags where slug='personal-care'), ARRAY['local']::lane[], ARRAY['haircut','fade','mens cut','barbershop']::text[], true, 9001),
  ('hair-salon', 'Hair Salon', (select id from tags where slug='personal-care'), ARRAY['local']::lane[], ARRAY['stylist','womens cut','blowout']::text[], true, 9002),
  ('hair-color', 'Hair Color', (select id from tags where slug='personal-care'), ARRAY['local']::lane[], ARRAY['balayage','highlights','dye']::text[], true, 9003),
  ('hair-extensions', 'Hair Extensions', (select id from tags where slug='personal-care'), ARRAY['local']::lane[], ARRAY['weave','tape ins','wigs']::text[], true, 9004),
  ('nails', 'Nails', (select id from tags where slug='personal-care'), ARRAY['local']::lane[], ARRAY['manicure','pedicure','gel nails','acrylics','nail salon']::text[], true, 9005),
  ('lashes', 'Lashes', (select id from tags where slug='personal-care'), ARRAY['local']::lane[], ARRAY['eyelash extensions','lash lift','lashes']::text[], true, 9006),
  ('brows', 'Brows', (select id from tags where slug='personal-care'), ARRAY['local']::lane[], ARRAY['microblading','brow lamination','threading','waxing brows']::text[], true, 9007),
  ('waxing-and-hair-removal', 'Waxing & Hair Removal', (select id from tags where slug='personal-care'), ARRAY['local']::lane[], ARRAY['wax','laser hair removal','sugaring']::text[], true, 9008),
  ('facials-and-skincare', 'Facials & Skincare', (select id from tags where slug='personal-care'), ARRAY['local']::lane[], ARRAY['esthetician','facial','hydrafacial','chemical peel']::text[], true, 9009),
  ('massage', 'Massage', (select id from tags where slug='personal-care'), ARRAY['local']::lane[], ARRAY['deep tissue','swedish','sports massage','massage therapy']::text[], true, 9010),
  ('day-spa', 'Day Spa', (select id from tags where slug='personal-care'), ARRAY['local']::lane[], ARRAY['spa day','spa package','sauna']::text[], true, 9011),
  ('tanning', 'Tanning', (select id from tags where slug='personal-care'), ARRAY['local']::lane[], ARRAY['spray tan','tanning salon','sunless']::text[], true, 9012),
  ('makeup-artist', 'Makeup Artist', (select id from tags where slug='personal-care'), ARRAY['local']::lane[], ARRAY['mua','bridal makeup','glam']::text[], true, 9013),
  ('tattoo', 'Tattoo', (select id from tags where slug='personal-care'), ARRAY['local']::lane[], ARRAY['tattoo shop','ink','tattoo artist']::text[], true, 9014),
  ('piercing', 'Piercing', (select id from tags where slug='personal-care'), ARRAY['local']::lane[], ARRAY['body piercing','ear piercing']::text[], true, 9015),
  ('permanent-makeup', 'Permanent Makeup', (select id from tags where slug='personal-care'), ARRAY['local']::lane[], ARRAY['pmu','lip blush','powder brows']::text[], true, 9016),
  ('teeth-whitening', 'Teeth Whitening', (select id from tags where slug='personal-care'), ARRAY['local']::lane[], ARRAY['whitening','cosmetic whitening']::text[], true, 9017),
  ('barber-and-beard-care', 'Barber & Beard Care', (select id from tags where slug='personal-care'), ARRAY['local','maker']::lane[], ARRAY['beard trim','hot shave','beard oil']::text[], true, 9018);

-- Health & Wellness
insert into tags (slug, label, parent_id, lanes, synonyms, selectable, sort_order) values
  ('dermatology', 'Dermatology', (select id from tags where slug='health-and-wellness'), ARRAY['local']::lane[], ARRAY['skin doctor','mole check','acne treatment']::text[], true, 10001),
  ('podiatry-and-foot-care', 'Podiatry & Foot Care', (select id from tags where slug='health-and-wellness'), ARRAY['local']::lane[], ARRAY['foot doctor','orthotics']::text[], true, 10002),
  ('womens-health', 'Womens Health', (select id from tags where slug='health-and-wellness'), ARRAY['local']::lane[], ARRAY['obgyn','womens clinic']::text[], true, 10003),
  ('mens-health', 'Mens Health', (select id from tags where slug='health-and-wellness'), ARRAY['local']::lane[], ARRAY['trt','mens clinic','hormone therapy']::text[], true, 10004),
  ('hair-restoration', 'Hair Restoration', (select id from tags where slug='health-and-wellness'), ARRAY['local']::lane[], ARRAY['hair transplant','prp hair','thinning']::text[], true, 10005),
  ('chiropractic', 'Chiropractic', (select id from tags where slug='health-and-wellness'), ARRAY['local']::lane[], ARRAY['chiropractor','adjustment','spinal']::text[], true, 10006),
  ('physical-therapy', 'Physical Therapy', (select id from tags where slug='health-and-wellness'), ARRAY['local']::lane[], ARRAY['pt','rehab','dry needling']::text[], true, 10007),
  ('acupuncture', 'Acupuncture', (select id from tags where slug='health-and-wellness'), ARRAY['local']::lane[], ARRAY['dry needling','tcm','cupping']::text[], true, 10008),
  ('dental', 'Dental', (select id from tags where slug='health-and-wellness'), ARRAY['local']::lane[], ARRAY['dentist','cleaning','teeth cleaning','checkup']::text[], true, 10009),
  ('orthodontics', 'Orthodontics', (select id from tags where slug='health-and-wellness'), ARRAY['local']::lane[], ARRAY['braces','invisalign','aligners']::text[], true, 10010),
  ('optometry', 'Optometry', (select id from tags where slug='health-and-wellness'), ARRAY['local']::lane[], ARRAY['eye exam','glasses','contacts','optical']::text[], true, 10011),
  ('med-spa', 'Med Spa', (select id from tags where slug='health-and-wellness'), ARRAY['local']::lane[], ARRAY['botox','filler','injectables','aesthetics']::text[], true, 10012),
  ('iv-therapy', 'IV Therapy', (select id from tags where slug='health-and-wellness'), ARRAY['local']::lane[], ARRAY['iv drip','hydration therapy','vitamin drip']::text[], true, 10013),
  ('cryotherapy-and-recovery', 'Cryotherapy & Recovery', (select id from tags where slug='health-and-wellness'), ARRAY['local']::lane[], ARRAY['cold plunge','cryo','compression','recovery lounge']::text[], true, 10014),
  ('float-therapy', 'Float Therapy', (select id from tags where slug='health-and-wellness'), ARRAY['local']::lane[], ARRAY['sensory deprivation','float tank']::text[], true, 10015),
  ('hearing', 'Hearing', (select id from tags where slug='health-and-wellness'), ARRAY['local']::lane[], ARRAY['hearing test','hearing aids','audiology']::text[], true, 10016),
  ('weight-and-nutrition-coaching', 'Weight & Nutrition Coaching', (select id from tags where slug='health-and-wellness'), ARRAY['local']::lane[], ARRAY['dietitian','nutritionist','meal coaching']::text[], true, 10017),
  ('primary-and-urgent-care', 'Primary & Urgent Care', (select id from tags where slug='health-and-wellness'), ARRAY['local']::lane[], ARRAY['walk in clinic','urgent care','checkup']::text[], true, 10018),
  ('lab-and-screening', 'Lab & Screening', (select id from tags where slug='health-and-wellness'), ARRAY['local']::lane[], ARRAY['blood work','health screening','panel']::text[], true, 10019),
  ('counseling-and-therapy', 'Counseling & Therapy', (select id from tags where slug='health-and-wellness'), ARRAY['local','digital']::lane[], ARRAY['therapist','mental health','talk therapy']::text[], true, 10020),
  ('sleep-and-breathwork', 'Sleep & Breathwork', (select id from tags where slug='health-and-wellness'), ARRAY['local','digital']::lane[], ARRAY['breathwork','sleep coaching','meditation session']::text[], true, 10021);

-- Fitness
insert into tags (slug, label, parent_id, lanes, synonyms, selectable, sort_order) values
  ('rowing-and-erg', 'Rowing & Erg', (select id from tags where slug='fitness'), ARRAY['local']::lane[], ARRAY['rowing studio','erg class']::text[], true, 11001),
  ('stretch-and-mobility', 'Stretch & Mobility', (select id from tags where slug='fitness'), ARRAY['local']::lane[], ARRAY['assisted stretching','mobility session']::text[], true, 11002),
  ('pickleball-and-courts', 'Pickleball & Courts', (select id from tags where slug='fitness'), ARRAY['local']::lane[], ARRAY['pickleball','court rental','tennis court']::text[], true, 11003),
  ('indoor-golf-league', 'Indoor Golf League', (select id from tags where slug='fitness'), ARRAY['local']::lane[], ARRAY['golf league','sim league']::text[], true, 11004),
  ('gym-membership', 'Gym Membership', (select id from tags where slug='fitness'), ARRAY['local']::lane[], ARRAY['fitness center','health club','gym']::text[], true, 11005),
  ('personal-training', 'Personal Training', (select id from tags where slug='fitness'), ARRAY['local','digital']::lane[], ARRAY['trainer','one on one training','pt session']::text[], true, 11006),
  ('group-fitness', 'Group Fitness', (select id from tags where slug='fitness'), ARRAY['local']::lane[], ARRAY['bootcamp','hiit','group class']::text[], true, 11007),
  ('crossfit', 'CrossFit', (select id from tags where slug='fitness'), ARRAY['local']::lane[], ARRAY['box','wod','functional fitness']::text[], true, 11008),
  ('yoga', 'Yoga', (select id from tags where slug='fitness'), ARRAY['local','digital']::lane[], ARRAY['hot yoga','vinyasa','yoga class']::text[], true, 11009),
  ('pilates', 'Pilates', (select id from tags where slug='fitness'), ARRAY['local']::lane[], ARRAY['reformer','mat pilates']::text[], true, 11010),
  ('barre', 'Barre', (select id from tags where slug='fitness'), ARRAY['local']::lane[], ARRAY['barre class']::text[], true, 11011),
  ('spin-and-cycling-studio', 'Spin & Cycling Studio', (select id from tags where slug='fitness'), ARRAY['local']::lane[], ARRAY['spin class','indoor cycling']::text[], true, 11012),
  ('boxing-and-kickboxing', 'Boxing & Kickboxing', (select id from tags where slug='fitness'), ARRAY['local']::lane[], ARRAY['boxing gym','muay thai','kickboxing']::text[], true, 11013),
  ('martial-arts', 'Martial Arts', (select id from tags where slug='fitness'), ARRAY['local']::lane[], ARRAY['bjj','jiu jitsu','karate','taekwondo','mma']::text[], true, 11014),
  ('climbing-gym', 'Climbing Gym', (select id from tags where slug='fitness'), ARRAY['local']::lane[], ARRAY['bouldering','rock climbing','climbing']::text[], true, 11015),
  ('swim-and-aquatics', 'Swim & Aquatics', (select id from tags where slug='fitness'), ARRAY['local']::lane[], ARRAY['swim lessons','lap swim','pool']::text[], true, 11016),
  ('dance-fitness', 'Dance Fitness', (select id from tags where slug='fitness'), ARRAY['local']::lane[], ARRAY['zumba','dance cardio']::text[], true, 11017),
  ('run-club-and-training', 'Run Club & Training', (select id from tags where slug='fitness'), ARRAY['local']::lane[], ARRAY['running group','marathon training']::text[], true, 11018),
  ('golf-simulator-and-range', 'Golf Simulator & Range', (select id from tags where slug='fitness'), ARRAY['local']::lane[], ARRAY['driving range','golf sim','launch monitor']::text[], true, 11019);

-- Entertainment
insert into tags (slug, label, parent_id, lanes, synonyms, selectable, sort_order) values
  ('movie-theater', 'Movie Theater', (select id from tags where slug='entertainment'), ARRAY['local']::lane[], ARRAY['cinema','movies','film']::text[], true, 12001),
  ('bowling', 'Bowling', (select id from tags where slug='entertainment'), ARRAY['local']::lane[], ARRAY['bowling alley','lanes']::text[], true, 12002),
  ('arcade', 'Arcade', (select id from tags where slug='entertainment'), ARRAY['local']::lane[], ARRAY['barcade','game arcade','pinball']::text[], true, 12003),
  ('escape-room', 'Escape Room', (select id from tags where slug='entertainment'), ARRAY['local']::lane[], ARRAY['escape game','puzzle room']::text[], true, 12004),
  ('axe-throwing', 'Axe Throwing', (select id from tags where slug='entertainment'), ARRAY['local']::lane[], ARRAY['hatchet throwing','axe bar']::text[], true, 12005),
  ('mini-golf', 'Mini Golf', (select id from tags where slug='entertainment'), ARRAY['local']::lane[], ARRAY['putt putt','miniature golf']::text[], true, 12006),
  ('go-karts', 'Go Karts', (select id from tags where slug='entertainment'), ARRAY['local']::lane[], ARRAY['karting','racing track']::text[], true, 12007),
  ('laser-tag', 'Laser Tag', (select id from tags where slug='entertainment'), ARRAY['local']::lane[], ARRAY['lasertag']::text[], true, 12008),
  ('pool-and-billiards', 'Pool & Billiards', (select id from tags where slug='entertainment'), ARRAY['local']::lane[], ARRAY['pool hall','billiards','snooker']::text[], true, 12009),
  ('vr-experience', 'VR Experience', (select id from tags where slug='entertainment'), ARRAY['local']::lane[], ARRAY['virtual reality','vr arcade']::text[], true, 12010),
  ('theater-and-performing-arts', 'Theater & Performing Arts', (select id from tags where slug='entertainment'), ARRAY['local']::lane[], ARRAY['playhouse','stage show','musical']::text[], true, 12011),
  ('concerts-and-shows', 'Concerts & Shows', (select id from tags where slug='entertainment'), ARRAY['local']::lane[], ARRAY['live show','tour','gig']::text[], true, 12012),
  ('museums-and-galleries', 'Museums & Galleries', (select id from tags where slug='entertainment'), ARRAY['local']::lane[], ARRAY['museum','art gallery','exhibit']::text[], true, 12013),
  ('zoo-and-aquarium', 'Zoo & Aquarium', (select id from tags where slug='entertainment'), ARRAY['local']::lane[], ARRAY['zoo','aquarium','wildlife park']::text[], true, 12014),
  ('amusement-and-water-park', 'Amusement & Water Park', (select id from tags where slug='entertainment'), ARRAY['local']::lane[], ARRAY['theme park','water park','rides']::text[], true, 12015),
  ('trampoline-park', 'Trampoline Park', (select id from tags where slug='entertainment'), ARRAY['local']::lane[], ARRAY['jump park','ninja course']::text[], true, 12016),
  ('sporting-event', 'Sporting Event', (select id from tags where slug='entertainment'), ARRAY['local']::lane[], ARRAY['game tickets','match','stadium']::text[], true, 12017),
  ('casino-and-gaming', 'Casino & Gaming', (select id from tags where slug='entertainment'), ARRAY['local']::lane[], ARRAY['gaming floor','casino']::text[], true, 12018);

-- Activities & Outdoors
insert into tags (slug, label, parent_id, lanes, synonyms, selectable, sort_order) values
  ('ski-and-snowboard', 'Ski & Snowboard', (select id from tags where slug='activities-and-outdoors'), ARRAY['local']::lane[], ARRAY['lift ticket','ski pass','snowboarding']::text[], true, 13001),
  ('ski-and-board-tuning', 'Ski & Board Tuning', (select id from tags where slug='activities-and-outdoors'), ARRAY['local']::lane[], ARRAY['wax','edge tune','binding mount']::text[], true, 13002),
  ('snowmobile-and-tours', 'Snowmobile & Tours', (select id from tags where slug='activities-and-outdoors'), ARRAY['local']::lane[], ARRAY['sled tour','snowmobiling']::text[], true, 13003),
  ('hiking-and-guided-tours', 'Hiking & Guided Tours', (select id from tags where slug='activities-and-outdoors'), ARRAY['local']::lane[], ARRAY['guided hike','trail tour','backpacking']::text[], true, 13004),
  ('rafting-and-kayaking', 'Rafting & Kayaking', (select id from tags where slug='activities-and-outdoors'), ARRAY['local']::lane[], ARRAY['whitewater','paddle','canoe']::text[], true, 13005),
  ('paddleboard-and-surf', 'Paddleboard & Surf', (select id from tags where slug='activities-and-outdoors'), ARRAY['local']::lane[], ARRAY['sup','surf lesson','paddleboarding']::text[], true, 13006),
  ('boat-and-jet-ski-rental', 'Boat & Jet Ski Rental', (select id from tags where slug='activities-and-outdoors'), ARRAY['local']::lane[], ARRAY['boat rental','watercraft','wave runner']::text[], true, 13007),
  ('fishing-charter-and-guide', 'Fishing Charter & Guide', (select id from tags where slug='activities-and-outdoors'), ARRAY['local']::lane[], ARRAY['fly fishing','guided fishing','charter']::text[], true, 13008),
  ('hunting-and-range', 'Hunting & Range', (select id from tags where slug='activities-and-outdoors'), ARRAY['local']::lane[], ARRAY['shooting range','gun range','archery']::text[], true, 13009),
  ('atv-and-off-road', 'ATV & Off Road', (select id from tags where slug='activities-and-outdoors'), ARRAY['local']::lane[], ARRAY['utv','side by side','offroad tour']::text[], true, 13010),
  ('camping-and-glamping', 'Camping & Glamping', (select id from tags where slug='activities-and-outdoors'), ARRAY['local']::lane[], ARRAY['campsite','yurt','glamping']::text[], true, 13011),
  ('bike-rental-and-tours', 'Bike Rental & Tours', (select id from tags where slug='activities-and-outdoors'), ARRAY['local']::lane[], ARRAY['e bike','mountain bike rental','bike tour']::text[], true, 13012),
  ('horseback-riding', 'Horseback Riding', (select id from tags where slug='activities-and-outdoors'), ARRAY['local']::lane[], ARRAY['trail ride','equestrian','stables']::text[], true, 13013),
  ('hot-air-balloon-and-flight', 'Hot Air Balloon & Flight', (select id from tags where slug='activities-and-outdoors'), ARRAY['local']::lane[], ARRAY['scenic flight','balloon ride','discovery flight']::text[], true, 13014),
  ('skydiving-and-adventure', 'Skydiving & Adventure', (select id from tags where slug='activities-and-outdoors'), ARRAY['local']::lane[], ARRAY['tandem jump','bungee','zipline']::text[], true, 13015),
  ('gun-and-archery-lessons', 'Gun & Archery Lessons', (select id from tags where slug='activities-and-outdoors'), ARRAY['local']::lane[], ARRAY['firearms training','ccw class','archery lesson']::text[], true, 13016);

-- Events & Celebrations
insert into tags (slug, label, parent_id, lanes, synonyms, selectable, sort_order) values
  ('officiant-and-ceremony', 'Officiant & Ceremony', (select id from tags where slug='events-and-celebrations'), ARRAY['local']::lane[], ARRAY['wedding officiant','ceremony']::text[], true, 14001),
  ('bartending-service', 'Bartending Service', (select id from tags where slug='events-and-celebrations'), ARRAY['local']::lane[], ARRAY['mobile bar','event bartender']::text[], true, 14002),
  ('transportation-and-limo', 'Transportation & Limo', (select id from tags where slug='events-and-celebrations'), ARRAY['local']::lane[], ARRAY['party bus','limo','shuttle']::text[], true, 14003),
  ('corporate-events', 'Corporate Events', (select id from tags where slug='events-and-celebrations'), ARRAY['local']::lane[], ARRAY['team building','company party','offsite']::text[], true, 14004),
  ('event-venue', 'Event Venue', (select id from tags where slug='events-and-celebrations'), ARRAY['local']::lane[], ARRAY['reception hall','event space','banquet']::text[], true, 14005),
  ('wedding-services', 'Wedding Services', (select id from tags where slug='events-and-celebrations'), ARRAY['local']::lane[], ARRAY['bridal','wedding planning','officiant']::text[], true, 14006),
  ('photography', 'Photography', (select id from tags where slug='events-and-celebrations'), ARRAY['local','maker']::lane[], ARRAY['photographer','portraits','headshots','photo session']::text[], true, 14007),
  ('videography', 'Videography', (select id from tags where slug='events-and-celebrations'), ARRAY['local','maker']::lane[], ARRAY['videographer','event video','film']::text[], true, 14008),
  ('dj-and-entertainment', 'DJ & Entertainment', (select id from tags where slug='events-and-celebrations'), ARRAY['local']::lane[], ARRAY['event dj','emcee','party dj']::text[], true, 14009),
  ('live-band', 'Live Band', (select id from tags where slug='events-and-celebrations'), ARRAY['local']::lane[], ARRAY['wedding band','cover band']::text[], true, 14010),
  ('florist', 'Florist', (select id from tags where slug='events-and-celebrations'), ARRAY['local','maker']::lane[], ARRAY['flowers','bouquet','floral arrangement']::text[], true, 14011),
  ('balloons-and-decor', 'Balloons & Decor', (select id from tags where slug='events-and-celebrations'), ARRAY['local','maker']::lane[], ARRAY['balloon garland','party decor','backdrop']::text[], true, 14012),
  ('party-rentals', 'Party Rentals', (select id from tags where slug='events-and-celebrations'), ARRAY['local']::lane[], ARRAY['tent rental','table rental','chair rental','bounce house']::text[], true, 14013),
  ('photo-booth', 'Photo Booth', (select id from tags where slug='events-and-celebrations'), ARRAY['local']::lane[], ARRAY['360 booth','photobooth']::text[], true, 14014),
  ('invitations-and-stationery', 'Invitations & Stationery', (select id from tags where slug='events-and-celebrations'), ARRAY['maker']::lane[], ARRAY['wedding invites','custom cards','calligraphy']::text[], true, 14015),
  ('cake-and-dessert-table', 'Cake & Dessert Table', (select id from tags where slug='events-and-celebrations'), ARRAY['local','maker']::lane[], ARRAY['wedding cake','dessert bar']::text[], true, 14016),
  ('event-catering', 'Event Catering', (select id from tags where slug='events-and-celebrations'), ARRAY['local']::lane[], ARRAY['catering','buffet service','food service']::text[], true, 14017),
  ('fireworks-and-effects', 'Fireworks & Effects', (select id from tags where slug='events-and-celebrations'), ARRAY['local']::lane[], ARRAY['pyro','cold sparks','sparklers']::text[], true, 14018);

-- Retail — Apparel
insert into tags (slug, label, parent_id, lanes, synonyms, selectable, sort_order) values
  ('womens-clothing', 'Womens Clothing', (select id from tags where slug='retail-apparel'), ARRAY['local','maker']::lane[], ARRAY['womenswear','dresses','boutique']::text[], true, 15001),
  ('mens-clothing', 'Mens Clothing', (select id from tags where slug='retail-apparel'), ARRAY['local','maker']::lane[], ARRAY['menswear','shirts','suits']::text[], true, 15002),
  ('streetwear', 'Streetwear', (select id from tags where slug='retail-apparel'), ARRAY['local','maker']::lane[], ARRAY['hypebeast','street style','graphic tees']::text[], true, 15003),
  ('vintage-and-thrift', 'Vintage & Thrift', (select id from tags where slug='retail-apparel'), ARRAY['local']::lane[], ARRAY['secondhand','consignment','thrift store']::text[], true, 15004),
  ('denim', 'Denim', (select id from tags where slug='retail-apparel'), ARRAY['local','maker']::lane[], ARRAY['jeans','selvedge']::text[], true, 15005),
  ('activewear', 'Activewear', (select id from tags where slug='retail-apparel'), ARRAY['local','maker']::lane[], ARRAY['athleisure','workout clothes','leggings']::text[], true, 15006),
  ('swimwear', 'Swimwear', (select id from tags where slug='retail-apparel'), ARRAY['local','maker']::lane[], ARRAY['swimsuits','bikini','board shorts']::text[], true, 15007),
  ('outerwear', 'Outerwear', (select id from tags where slug='retail-apparel'), ARRAY['local','maker']::lane[], ARRAY['jackets','coats','parka']::text[], true, 15008),
  ('footwear', 'Footwear', (select id from tags where slug='retail-apparel'), ARRAY['local','maker']::lane[], ARRAY['shoes','sneakers','boots']::text[], true, 15009),
  ('sneakers-and-collectibles', 'Sneakers & Collectibles', (select id from tags where slug='retail-apparel'), ARRAY['local','maker']::lane[], ARRAY['kicks','hype sneakers','grails']::text[], true, 15010),
  ('western-and-workwear', 'Western & Workwear', (select id from tags where slug='retail-apparel'), ARRAY['local','maker']::lane[], ARRAY['boots','cowboy','carhartt style','ranch wear']::text[], true, 15011),
  ('hats-and-headwear', 'Hats & Headwear', (select id from tags where slug='retail-apparel'), ARRAY['local','maker']::lane[], ARRAY['caps','beanies','snapback','custom hats']::text[], true, 15012),
  ('custom-apparel-and-embroidery', 'Custom Apparel & Embroidery', (select id from tags where slug='retail-apparel'), ARRAY['local','maker']::lane[], ARRAY['screen printing','embroidery','custom shirts','team gear']::text[], true, 15013),
  ('kids-clothing', 'Kids Clothing', (select id from tags where slug='retail-apparel'), ARRAY['local','maker']::lane[], ARRAY['childrens clothes','baby clothes']::text[], true, 15014),
  ('formal-and-bridal-wear', 'Formal & Bridal Wear', (select id from tags where slug='retail-apparel'), ARRAY['local']::lane[], ARRAY['tuxedo','wedding dress','gown']::text[], true, 15015),
  ('uniforms-and-team-kits', 'Uniforms & Team Kits', (select id from tags where slug='retail-apparel'), ARRAY['local','maker']::lane[], ARRAY['team uniforms','work uniforms','jerseys']::text[], true, 15016),
  ('tailoring-and-alterations', 'Tailoring & Alterations', (select id from tags where slug='retail-apparel'), ARRAY['local']::lane[], ARRAY['seamstress','hemming','suit alterations']::text[], true, 15017);

-- Retail — Home & Lifestyle
insert into tags (slug, label, parent_id, lanes, synonyms, selectable, sort_order) values
  ('furniture', 'Furniture', (select id from tags where slug='retail-home-and-lifestyle'), ARRAY['local','maker']::lane[], ARRAY['couches','tables','home furniture']::text[], true, 16001),
  ('custom-woodwork', 'Custom Woodwork', (select id from tags where slug='retail-home-and-lifestyle'), ARRAY['maker']::lane[], ARRAY['woodworking','live edge','joinery','custom table']::text[], true, 16002),
  ('home-decor', 'Home Decor', (select id from tags where slug='retail-home-and-lifestyle'), ARRAY['local','maker']::lane[], ARRAY['decor','wall art','accents']::text[], true, 16003),
  ('rugs-and-textiles', 'Rugs & Textiles', (select id from tags where slug='retail-home-and-lifestyle'), ARRAY['local','maker']::lane[], ARRAY['area rug','throw','blanket']::text[], true, 16004),
  ('bedding-and-linens', 'Bedding & Linens', (select id from tags where slug='retail-home-and-lifestyle'), ARRAY['local','maker']::lane[], ARRAY['sheets','duvet','pillows']::text[], true, 16005),
  ('kitchenware', 'Kitchenware', (select id from tags where slug='retail-home-and-lifestyle'), ARRAY['local','maker']::lane[], ARRAY['cookware','knives','cutting board']::text[], true, 16006),
  ('ceramics-and-pottery', 'Ceramics & Pottery', (select id from tags where slug='retail-home-and-lifestyle'), ARRAY['maker']::lane[], ARRAY['handmade mugs','stoneware','pottery']::text[], true, 16007),
  ('glassware-and-blown-glass', 'Glassware & Blown Glass', (select id from tags where slug='retail-home-and-lifestyle'), ARRAY['maker']::lane[], ARRAY['glassblowing','hand blown']::text[], true, 16008),
  ('candles', 'Candles', (select id from tags where slug='retail-home-and-lifestyle'), ARRAY['maker']::lane[], ARRAY['soy candles','scented candles','wax melts']::text[], true, 16009),
  ('soap-and-bath', 'Soap & Bath', (select id from tags where slug='retail-home-and-lifestyle'), ARRAY['maker']::lane[], ARRAY['handmade soap','bath bombs','body butter']::text[], true, 16010),
  ('skincare-and-beauty-products', 'Skincare & Beauty Products', (select id from tags where slug='retail-home-and-lifestyle'), ARRAY['local','maker']::lane[], ARRAY['serum','moisturizer','cosmetics']::text[], true, 16011),
  ('fragrance', 'Fragrance', (select id from tags where slug='retail-home-and-lifestyle'), ARRAY['local','maker']::lane[], ARRAY['perfume','cologne','scent']::text[], true, 16012),
  ('plants-and-planters', 'Plants & Planters', (select id from tags where slug='retail-home-and-lifestyle'), ARRAY['local','maker']::lane[], ARRAY['houseplants','succulents','pots']::text[], true, 16013),
  ('lighting-and-lamps', 'Lighting & Lamps', (select id from tags where slug='retail-home-and-lifestyle'), ARRAY['local','maker']::lane[], ARRAY['lamps','fixtures','neon signs']::text[], true, 16014),
  ('metalwork-and-forged', 'Metalwork & Forged', (select id from tags where slug='retail-home-and-lifestyle'), ARRAY['maker']::lane[], ARRAY['blacksmith','forged','metal art','knifemaking']::text[], true, 16015),
  ('leather-goods', 'Leather Goods', (select id from tags where slug='retail-home-and-lifestyle'), ARRAY['maker']::lane[], ARRAY['wallets','belts','leather bags','tooled leather']::text[], true, 16016),
  ('stationery-and-paper', 'Stationery & Paper', (select id from tags where slug='retail-home-and-lifestyle'), ARRAY['maker']::lane[], ARRAY['notebooks','journals','prints']::text[], true, 16017),
  ('art-and-prints', 'Art & Prints', (select id from tags where slug='retail-home-and-lifestyle'), ARRAY['maker']::lane[], ARRAY['original art','fine art print','poster']::text[], true, 16018);

-- Jewelry & Accessories
insert into tags (slug, label, parent_id, lanes, synonyms, selectable, sort_order) values
  ('custom-engraving', 'Custom Engraving', (select id from tags where slug='jewelry-and-accessories'), ARRAY['local','maker']::lane[], ARRAY['engraving','laser engraving','personalized']::text[], true, 17001),
  ('body-jewelry', 'Body Jewelry', (select id from tags where slug='jewelry-and-accessories'), ARRAY['local','maker']::lane[], ARRAY['piercing jewelry','gauges']::text[], true, 17002),
  ('mens-accessories', 'Mens Accessories', (select id from tags where slug='jewelry-and-accessories'), ARRAY['local','maker']::lane[], ARRAY['cufflinks','tie bar','money clip']::text[], true, 17003),
  ('hair-accessories', 'Hair Accessories', (select id from tags where slug='jewelry-and-accessories'), ARRAY['local','maker']::lane[], ARRAY['scrunchies','clips','headbands']::text[], true, 17004),
  ('fine-jewelry', 'Fine Jewelry', (select id from tags where slug='jewelry-and-accessories'), ARRAY['local','maker']::lane[], ARRAY['diamonds','gold','engagement ring']::text[], true, 17005),
  ('handmade-jewelry', 'Handmade Jewelry', (select id from tags where slug='jewelry-and-accessories'), ARRAY['maker']::lane[], ARRAY['artisan jewelry','beaded','wire wrap']::text[], true, 17006),
  ('silver-and-turquoise', 'Silver & Turquoise', (select id from tags where slug='jewelry-and-accessories'), ARRAY['local','maker']::lane[], ARRAY['southwest jewelry','native style','sterling']::text[], true, 17007),
  ('watches', 'Watches', (select id from tags where slug='jewelry-and-accessories'), ARRAY['local','maker']::lane[], ARRAY['timepiece','watch shop']::text[], true, 17008),
  ('watch-repair', 'Watch Repair', (select id from tags where slug='jewelry-and-accessories'), ARRAY['local']::lane[], ARRAY['watch service','battery replacement','band sizing']::text[], true, 17009),
  ('jewelry-repair-and-custom', 'Jewelry Repair & Custom', (select id from tags where slug='jewelry-and-accessories'), ARRAY['local']::lane[], ARRAY['ring sizing','custom ring','resetting']::text[], true, 17010),
  ('engagement-and-bridal', 'Engagement & Bridal', (select id from tags where slug='jewelry-and-accessories'), ARRAY['local','maker']::lane[], ARRAY['wedding bands','engagement','bridal set']::text[], true, 17011),
  ('bags-and-purses', 'Bags & Purses', (select id from tags where slug='jewelry-and-accessories'), ARRAY['local','maker']::lane[], ARRAY['handbag','tote','backpack']::text[], true, 17012),
  ('sunglasses-and-eyewear', 'Sunglasses & Eyewear', (select id from tags where slug='jewelry-and-accessories'), ARRAY['local','maker']::lane[], ARRAY['shades','frames']::text[], true, 17013),
  ('belts-and-small-leather', 'Belts & Small Leather', (select id from tags where slug='jewelry-and-accessories'), ARRAY['maker']::lane[], ARRAY['wallet','card holder','keychain']::text[], true, 17014),
  ('pins-patches-and-enamel', 'Pins, Patches & Enamel', (select id from tags where slug='jewelry-and-accessories'), ARRAY['maker']::lane[], ARRAY['enamel pin','patches','stickers']::text[], true, 17015);

-- Retail — Gear & Hobby
insert into tags (slug, label, parent_id, lanes, synonyms, selectable, sort_order) values
  ('outdoor-gear', 'Outdoor Gear', (select id from tags where slug='retail-gear-and-hobby'), ARRAY['local','maker']::lane[], ARRAY['camping gear','backpacking gear','hiking gear']::text[], true, 18001),
  ('ski-and-snowboard-shop', 'Ski & Snowboard Shop', (select id from tags where slug='retail-gear-and-hobby'), ARRAY['local','maker']::lane[], ARRAY['snow gear','boards','skis']::text[], true, 18002),
  ('bike-shop', 'Bike Shop', (select id from tags where slug='retail-gear-and-hobby'), ARRAY['local']::lane[], ARRAY['bicycle','bike repair','cycling']::text[], true, 18003),
  ('fishing-and-tackle', 'Fishing & Tackle', (select id from tags where slug='retail-gear-and-hobby'), ARRAY['local','maker']::lane[], ARRAY['fly shop','tackle','lures','rods']::text[], true, 18004),
  ('hunting-and-shooting', 'Hunting & Shooting', (select id from tags where slug='retail-gear-and-hobby'), ARRAY['local','maker']::lane[], ARRAY['firearms','ammo','optics','archery']::text[], true, 18005),
  ('water-sports-gear', 'Water Sports Gear', (select id from tags where slug='retail-gear-and-hobby'), ARRAY['local','maker']::lane[], ARRAY['wakeboard','kayak','paddleboard']::text[], true, 18006),
  ('golf-shop-and-fitting', 'Golf Shop & Fitting', (select id from tags where slug='retail-gear-and-hobby'), ARRAY['local']::lane[], ARRAY['club fitting','golf clubs','pro shop']::text[], true, 18007),
  ('running-and-shoe-fitting', 'Running & Shoe Fitting', (select id from tags where slug='retail-gear-and-hobby'), ARRAY['local']::lane[], ARRAY['gait analysis','running shoes']::text[], true, 18008),
  ('music-instruments', 'Music Instruments', (select id from tags where slug='retail-gear-and-hobby'), ARRAY['local','maker']::lane[], ARRAY['guitar shop','instrument repair','strings']::text[], true, 18009),
  ('records-and-vinyl', 'Records & Vinyl', (select id from tags where slug='retail-gear-and-hobby'), ARRAY['local','maker']::lane[], ARRAY['record store','vinyl','lps']::text[], true, 18010),
  ('comics-and-collectibles', 'Comics & Collectibles', (select id from tags where slug='retail-gear-and-hobby'), ARRAY['local','maker']::lane[], ARRAY['comic shop','trading cards','figures']::text[], true, 18011),
  ('trading-cards', 'Trading Cards', (select id from tags where slug='retail-gear-and-hobby'), ARRAY['local','maker']::lane[], ARRAY['sports cards','tcg','pokemon cards','breaks']::text[], true, 18012),
  ('board-games-and-tabletop', 'Board Games & Tabletop', (select id from tags where slug='retail-gear-and-hobby'), ARRAY['local','maker']::lane[], ARRAY['game shop','dnd','miniatures']::text[], true, 18013),
  ('video-games', 'Video Games', (select id from tags where slug='retail-gear-and-hobby'), ARRAY['local','maker']::lane[], ARRAY['game store','console','retro games']::text[], true, 18014),
  ('hobby-and-models', 'Hobby & Models', (select id from tags where slug='retail-gear-and-hobby'), ARRAY['local','maker']::lane[], ARRAY['rc cars','model kits','drones']::text[], true, 18015),
  ('craft-and-fabric-supply', 'Craft & Fabric Supply', (select id from tags where slug='retail-gear-and-hobby'), ARRAY['local','maker']::lane[], ARRAY['yarn','fabric store','quilting','sewing supply']::text[], true, 18016),
  ('art-supplies', 'Art Supplies', (select id from tags where slug='retail-gear-and-hobby'), ARRAY['local','maker']::lane[], ARRAY['paint','canvas','brushes']::text[], true, 18017),
  ('3d-printing-and-maker-supply', '3D Printing & Maker Supply', (select id from tags where slug='retail-gear-and-hobby'), ARRAY['maker','digital']::lane[], ARRAY['filament','resin printing','prototyping']::text[], true, 18018),
  ('tools-and-equipment', 'Tools & Equipment', (select id from tags where slug='retail-gear-and-hobby'), ARRAY['local','maker']::lane[], ARRAY['power tools','hand tools','tool rental']::text[], true, 18019),
  ('sporting-goods', 'Sporting Goods', (select id from tags where slug='retail-gear-and-hobby'), ARRAY['local','maker']::lane[], ARRAY['athletic gear','team sports','equipment']::text[], true, 18020);

-- Kids & Family
insert into tags (slug, label, parent_id, lanes, synonyms, selectable, sort_order) values
  ('kids-sports-leagues', 'Kids Sports Leagues', (select id from tags where slug='kids-and-family'), ARRAY['local']::lane[], ARRAY['youth sports','little league','rec league']::text[], true, 19001),
  ('music-and-theater-for-kids', 'Music & Theater for Kids', (select id from tags where slug='kids-and-family'), ARRAY['local']::lane[], ARRAY['kids choir','youth theater','kids band']::text[], true, 19002),
  ('kids-haircut-and-spa', 'Kids Haircut & Spa', (select id from tags where slug='kids-and-family'), ARRAY['local']::lane[], ARRAY['kids spa','princess party']::text[], true, 19003),
  ('family-entertainment-center', 'Family Entertainment Center', (select id from tags where slug='kids-and-family'), ARRAY['local']::lane[], ARRAY['fec','family fun center']::text[], true, 19004),
  ('childcare-and-daycare', 'Childcare & Daycare', (select id from tags where slug='kids-and-family'), ARRAY['local']::lane[], ARRAY['day care','preschool','nursery']::text[], true, 19005),
  ('babysitting-and-nanny', 'Babysitting & Nanny', (select id from tags where slug='kids-and-family'), ARRAY['local']::lane[], ARRAY['sitter','nanny','date night care']::text[], true, 19006),
  ('kids-activities', 'Kids Activities', (select id from tags where slug='kids-and-family'), ARRAY['local']::lane[], ARRAY['play place','indoor playground','kids gym']::text[], true, 19007),
  ('kids-classes', 'Kids Classes', (select id from tags where slug='kids-and-family'), ARRAY['local']::lane[], ARRAY['gymnastics','kids dance','tumbling']::text[], true, 19008),
  ('kids-haircuts', 'Kids Haircuts', (select id from tags where slug='kids-and-family'), ARRAY['local']::lane[], ARRAY['childrens haircut','first haircut']::text[], true, 19009),
  ('birthday-parties', 'Birthday Parties', (select id from tags where slug='kids-and-family'), ARRAY['local']::lane[], ARRAY['kids party','party package','party room']::text[], true, 19010),
  ('toys-and-games', 'Toys & Games', (select id from tags where slug='kids-and-family'), ARRAY['local','maker']::lane[], ARRAY['toy store','kids toys','wooden toys']::text[], true, 19011),
  ('baby-gear', 'Baby Gear', (select id from tags where slug='kids-and-family'), ARRAY['local','maker']::lane[], ARRAY['strollers','car seats','baby essentials']::text[], true, 19012),
  ('maternity-and-newborn', 'Maternity & Newborn', (select id from tags where slug='kids-and-family'), ARRAY['local','maker']::lane[], ARRAY['maternity photos','newborn','doula']::text[], true, 19013),
  ('summer-camps', 'Summer Camps', (select id from tags where slug='kids-and-family'), ARRAY['local']::lane[], ARRAY['day camp','kids camp','sports camp']::text[], true, 19014),
  ('tutoring', 'Tutoring', (select id from tags where slug='kids-and-family'), ARRAY['local','digital']::lane[], ARRAY['homework help','test prep','academic tutor']::text[], true, 19015),
  ('family-photography', 'Family Photography', (select id from tags where slug='kids-and-family'), ARRAY['local','maker']::lane[], ARRAY['family photos','mini session']::text[], true, 19016);

-- Pets
insert into tags (slug, label, parent_id, lanes, synonyms, selectable, sort_order) values
  ('mobile-grooming', 'Mobile Grooming', (select id from tags where slug='pets'), ARRAY['local']::lane[], ARRAY['mobile groomer','grooming van']::text[], true, 20001),
  ('pet-waste-removal', 'Pet Waste Removal', (select id from tags where slug='pets'), ARRAY['local']::lane[], ARRAY['poop scooping','yard cleanup']::text[], true, 20002),
  ('pet-memorial-and-cremation', 'Pet Memorial & Cremation', (select id from tags where slug='pets'), ARRAY['local']::lane[], ARRAY['pet cremation','memorial']::text[], true, 20003),
  ('pet-insurance-and-wellness-plans', 'Pet Insurance & Wellness Plans', (select id from tags where slug='pets'), ARRAY['local']::lane[], ARRAY['pet plan','wellness plan']::text[], true, 20004),
  ('dog-grooming', 'Dog Grooming', (select id from tags where slug='pets'), ARRAY['local']::lane[], ARRAY['groomer','pet grooming','dog bath']::text[], true, 20005),
  ('pet-boarding', 'Pet Boarding', (select id from tags where slug='pets'), ARRAY['local']::lane[], ARRAY['kennel','dog boarding','pet hotel']::text[], true, 20006),
  ('doggy-daycare', 'Doggy Daycare', (select id from tags where slug='pets'), ARRAY['local']::lane[], ARRAY['dog daycare','pet daycare']::text[], true, 20007),
  ('dog-training', 'Dog Training', (select id from tags where slug='pets'), ARRAY['local','digital']::lane[], ARRAY['obedience','puppy class','k9 training']::text[], true, 20008),
  ('dog-walking-and-sitting', 'Dog Walking & Sitting', (select id from tags where slug='pets'), ARRAY['local']::lane[], ARRAY['pet sitter','dog walker']::text[], true, 20009),
  ('veterinary', 'Veterinary', (select id from tags where slug='pets'), ARRAY['local']::lane[], ARRAY['vet','animal clinic','pet checkup']::text[], true, 20010),
  ('pet-supplies', 'Pet Supplies', (select id from tags where slug='pets'), ARRAY['local','maker']::lane[], ARRAY['pet food','pet store','treats']::text[], true, 20011),
  ('pet-treats-and-bakery', 'Pet Treats & Bakery', (select id from tags where slug='pets'), ARRAY['maker']::lane[], ARRAY['dog treats','pet bakery']::text[], true, 20012),
  ('pet-photography', 'Pet Photography', (select id from tags where slug='pets'), ARRAY['local','maker']::lane[], ARRAY['pet portraits','dog photos']::text[], true, 20013),
  ('aquarium-and-reptile', 'Aquarium & Reptile', (select id from tags where slug='pets'), ARRAY['local','maker']::lane[], ARRAY['fish store','reptile','terrarium']::text[], true, 20014),
  ('equine-services', 'Equine Services', (select id from tags where slug='pets'), ARRAY['local']::lane[], ARRAY['farrier','horse boarding','equine']::text[], true, 20015),
  ('custom-pet-gear', 'Custom Pet Gear', (select id from tags where slug='pets'), ARRAY['maker']::lane[], ARRAY['collars','leashes','pet beds']::text[], true, 20016);

-- Professional Services
insert into tags (slug, label, parent_id, lanes, synonyms, selectable, sort_order) values
  ('estate-and-probate', 'Estate & Probate', (select id from tags where slug='professional-services'), ARRAY['local','digital']::lane[], ARRAY['will','trust','estate planning']::text[], true, 21001),
  ('immigration-services', 'Immigration Services', (select id from tags where slug='professional-services'), ARRAY['local','digital']::lane[], ARRAY['visa help','immigration attorney']::text[], true, 21002),
  ('bookkeeping-cleanup', 'Bookkeeping Cleanup', (select id from tags where slug='professional-services'), ARRAY['local','digital']::lane[], ARRAY['catch up books','reconciliation']::text[], true, 21003),
  ('drone-and-aerial-services', 'Drone & Aerial Services', (select id from tags where slug='professional-services'), ARRAY['local','maker']::lane[], ARRAY['drone photography','aerial mapping','roof inspection']::text[], true, 21004),
  ('accounting-and-bookkeeping', 'Accounting & Bookkeeping', (select id from tags where slug='professional-services'), ARRAY['local','digital']::lane[], ARRAY['cpa','bookkeeper','quickbooks']::text[], true, 21005),
  ('tax-preparation', 'Tax Preparation', (select id from tags where slug='professional-services'), ARRAY['local','digital']::lane[], ARRAY['tax prep','tax filing','irs']::text[], true, 21006),
  ('legal-services', 'Legal Services', (select id from tags where slug='professional-services'), ARRAY['local','digital']::lane[], ARRAY['attorney','lawyer','consultation']::text[], true, 21007),
  ('insurance', 'Insurance', (select id from tags where slug='professional-services'), ARRAY['local']::lane[], ARRAY['insurance agent','policy quote','coverage']::text[], true, 21008),
  ('financial-planning', 'Financial Planning', (select id from tags where slug='professional-services'), ARRAY['local','digital']::lane[], ARRAY['advisor','retirement planning','wealth']::text[], true, 21009),
  ('real-estate', 'Real Estate', (select id from tags where slug='professional-services'), ARRAY['local']::lane[], ARRAY['realtor','agent','listing','home buying']::text[], true, 21010),
  ('home-inspection', 'Home Inspection', (select id from tags where slug='professional-services'), ARRAY['local']::lane[], ARRAY['inspector','pre purchase inspection']::text[], true, 21011),
  ('appraisal', 'Appraisal', (select id from tags where slug='professional-services'), ARRAY['local']::lane[], ARRAY['home appraisal','valuation']::text[], true, 21012),
  ('mortgage-and-lending', 'Mortgage & Lending', (select id from tags where slug='professional-services'), ARRAY['local']::lane[], ARRAY['loan officer','refinance','pre approval']::text[], true, 21013),
  ('title-and-escrow', 'Title & Escrow', (select id from tags where slug='professional-services'), ARRAY['local']::lane[], ARRAY['closing','title company']::text[], true, 21014),
  ('notary-and-signing', 'Notary & Signing', (select id from tags where slug='professional-services'), ARRAY['local']::lane[], ARRAY['notary public','mobile notary']::text[], true, 21015),
  ('printing-and-signs', 'Printing & Signs', (select id from tags where slug='professional-services'), ARRAY['local','maker']::lane[], ARRAY['print shop','banners','business cards','vinyl signs']::text[], true, 21016),
  ('shipping-and-mailbox', 'Shipping & Mailbox', (select id from tags where slug='professional-services'), ARRAY['local']::lane[], ARRAY['packing','mailbox rental','freight']::text[], true, 21017),
  ('it-and-computer-repair', 'IT & Computer Repair', (select id from tags where slug='professional-services'), ARRAY['local','digital']::lane[], ARRAY['computer repair','tech support','managed it']::text[], true, 21018),
  ('phone-and-device-repair', 'Phone & Device Repair', (select id from tags where slug='professional-services'), ARRAY['local']::lane[], ARRAY['screen repair','iphone repair','tablet repair']::text[], true, 21019),
  ('marketing-and-design', 'Marketing & Design', (select id from tags where slug='professional-services'), ARRAY['local','digital']::lane[], ARRAY['branding','logo design','social media management']::text[], true, 21020),
  ('web-development', 'Web Development', (select id from tags where slug='professional-services'), ARRAY['local','digital']::lane[], ARRAY['website build','web design','ecommerce build']::text[], true, 21021),
  ('photography-commercial', 'Photography — Commercial', (select id from tags where slug='professional-services'), ARRAY['local','maker']::lane[], ARRAY['product photos','real estate photos','corporate headshots']::text[], true, 21022),
  ('staffing-and-recruiting', 'Staffing & Recruiting', (select id from tags where slug='professional-services'), ARRAY['local','digital']::lane[], ARRAY['hiring','recruiter','temp staffing']::text[], true, 21023),
  ('translation-and-interpreting', 'Translation & Interpreting', (select id from tags where slug='professional-services'), ARRAY['local','digital']::lane[], ARRAY['translator','interpreter','spanish translation']::text[], true, 21024),
  ('consulting', 'Consulting', (select id from tags where slug='professional-services'), ARRAY['local','digital']::lane[], ARRAY['business consulting','strategy','advisory']::text[], true, 21025),
  ('coworking-and-office-space', 'Coworking & Office Space', (select id from tags where slug='professional-services'), ARRAY['local']::lane[], ARRAY['desk rental','office space','meeting room']::text[], true, 21026),
  ('storage', 'Storage', (select id from tags where slug='professional-services'), ARRAY['local']::lane[], ARRAY['self storage','storage unit']::text[], true, 21027),
  ('security-services', 'Security Services', (select id from tags where slug='professional-services'), ARRAY['local']::lane[], ARRAY['guard service','event security']::text[], true, 21028);

-- Education & Lessons
insert into tags (slug, label, parent_id, lanes, synonyms, selectable, sort_order) values
  ('fitness-certification', 'Fitness Certification', (select id from tags where slug='education-and-lessons'), ARRAY['local','digital']::lane[], ARRAY['personal trainer cert','coaching cert']::text[], true, 22001),
  ('real-estate-and-trade-licensing', 'Real Estate & Trade Licensing', (select id from tags where slug='education-and-lessons'), ARRAY['local','digital']::lane[], ARRAY['license course','exam course']::text[], true, 22002),
  ('firearms-and-safety-course', 'Firearms & Safety Course', (select id from tags where slug='education-and-lessons'), ARRAY['local']::lane[], ARRAY['gun safety','concealed carry class']::text[], true, 22003),
  ('first-aid-and-cpr', 'First Aid & CPR', (select id from tags where slug='education-and-lessons'), ARRAY['local']::lane[], ARRAY['cpr class','first aid cert']::text[], true, 22004),
  ('music-lessons', 'Music Lessons', (select id from tags where slug='education-and-lessons'), ARRAY['local','digital']::lane[], ARRAY['guitar lessons','piano lessons','voice lessons']::text[], true, 22005),
  ('art-classes', 'Art Classes', (select id from tags where slug='education-and-lessons'), ARRAY['local','digital']::lane[], ARRAY['painting class','drawing class','paint night']::text[], true, 22006),
  ('pottery-and-ceramics-class', 'Pottery & Ceramics Class', (select id from tags where slug='education-and-lessons'), ARRAY['local']::lane[], ARRAY['wheel throwing','pottery class']::text[], true, 22007),
  ('cooking-classes', 'Cooking Classes', (select id from tags where slug='education-and-lessons'), ARRAY['local','digital']::lane[], ARRAY['culinary class','cooking school','baking class']::text[], true, 22008),
  ('language-classes', 'Language Classes', (select id from tags where slug='education-and-lessons'), ARRAY['local','digital']::lane[], ARRAY['spanish class','esl','language school']::text[], true, 22009),
  ('dance-lessons', 'Dance Lessons', (select id from tags where slug='education-and-lessons'), ARRAY['local','digital']::lane[], ARRAY['salsa','ballroom','hip hop class']::text[], true, 22010),
  ('driving-school', 'Driving School', (select id from tags where slug='education-and-lessons'), ARRAY['local']::lane[], ARRAY['drivers ed','driving lessons']::text[], true, 22011),
  ('trade-and-certification', 'Trade & Certification', (select id from tags where slug='education-and-lessons'), ARRAY['local','digital']::lane[], ARRAY['welding class','cdl','osha','certification']::text[], true, 22012),
  ('photography-workshop', 'Photography Workshop', (select id from tags where slug='education-and-lessons'), ARRAY['local','digital']::lane[], ARRAY['photo workshop','lightroom class']::text[], true, 22013),
  ('woodworking-class', 'Woodworking Class', (select id from tags where slug='education-and-lessons'), ARRAY['local']::lane[], ARRAY['shop class','woodshop']::text[], true, 22014),
  ('sewing-and-craft-class', 'Sewing & Craft Class', (select id from tags where slug='education-and-lessons'), ARRAY['local','digital']::lane[], ARRAY['sewing lessons','quilting class','crafting workshop']::text[], true, 22015),
  ('coding-and-tech-class', 'Coding & Tech Class', (select id from tags where slug='education-and-lessons'), ARRAY['local','digital']::lane[], ARRAY['bootcamp','programming class','web dev course']::text[], true, 22016),
  ('business-and-finance-course', 'Business & Finance Course', (select id from tags where slug='education-and-lessons'), ARRAY['digital']::lane[], ARRAY['online course','masterclass','training']::text[], true, 22017),
  ('test-prep', 'Test Prep', (select id from tags where slug='education-and-lessons'), ARRAY['local','digital']::lane[], ARRAY['sat prep','act prep','exam prep']::text[], true, 22018);

-- Travel & Stays
insert into tags (slug, label, parent_id, lanes, synonyms, selectable, sort_order) values
  ('glamping-and-domes', 'Glamping & Domes', (select id from tags where slug='travel-and-stays'), ARRAY['local']::lane[], ARRAY['dome stay','treehouse','unique stay']::text[], true, 23001),
  ('ski-in-lodging', 'Ski-In Lodging', (select id from tags where slug='travel-and-stays'), ARRAY['local']::lane[], ARRAY['slopeside','ski lodging']::text[], true, 23002),
  ('group-and-retreat-venues', 'Group & Retreat Venues', (select id from tags where slug='travel-and-stays'), ARRAY['local']::lane[], ARRAY['retreat center','group lodging']::text[], true, 23003),
  ('pet-friendly-stays', 'Pet Friendly Stays', (select id from tags where slug='travel-and-stays'), ARRAY['local']::lane[], ARRAY['dog friendly hotel','pet friendly']::text[], true, 23004),
  ('long-stay-and-extended', 'Long Stay & Extended', (select id from tags where slug='travel-and-stays'), ARRAY['local']::lane[], ARRAY['extended stay','monthly rental']::text[], true, 23005),
  ('hotel', 'Hotel', (select id from tags where slug='travel-and-stays'), ARRAY['local']::lane[], ARRAY['lodging','hotel stay','room']::text[], true, 23006),
  ('boutique-and-bandb', 'Boutique & B&B', (select id from tags where slug='travel-and-stays'), ARRAY['local']::lane[], ARRAY['bed and breakfast','inn','guesthouse']::text[], true, 23007),
  ('vacation-rental', 'Vacation Rental', (select id from tags where slug='travel-and-stays'), ARRAY['local']::lane[], ARRAY['cabin','short term rental','condo']::text[], true, 23008),
  ('resort-and-lodge', 'Resort & Lodge', (select id from tags where slug='travel-and-stays'), ARRAY['local']::lane[], ARRAY['ski resort','mountain lodge','spa resort']::text[], true, 23009),
  ('campground-and-rv-park', 'Campground & RV Park', (select id from tags where slug='travel-and-stays'), ARRAY['local']::lane[], ARRAY['rv park','campsite','hookups']::text[], true, 23010),
  ('airport-parking-and-shuttle', 'Airport Parking & Shuttle', (select id from tags where slug='travel-and-stays'), ARRAY['local']::lane[], ARRAY['park and fly','shuttle service']::text[], true, 23011),
  ('tours-and-sightseeing', 'Tours & Sightseeing', (select id from tags where slug='travel-and-stays'), ARRAY['local']::lane[], ARRAY['city tour','guided tour','excursion']::text[], true, 23012),
  ('travel-agency', 'Travel Agency', (select id from tags where slug='travel-and-stays'), ARRAY['local','digital']::lane[], ARRAY['trip planning','travel booking']::text[], true, 23013),
  ('luggage-and-travel-gear', 'Luggage & Travel Gear', (select id from tags where slug='travel-and-stays'), ARRAY['local','maker']::lane[], ARRAY['suitcase','travel bag','packing cubes']::text[], true, 23014);

-- Digital & Creative
insert into tags (slug, label, parent_id, lanes, synonyms, selectable, sort_order) values
  ('sample-packs-and-loops', 'Sample Packs & Loops', (select id from tags where slug='digital-and-creative'), ARRAY['digital']::lane[], ARRAY['drum kit','sample pack','loops']::text[], true, 24001),
  ('video-luts-and-effects', 'Video LUTs & Effects', (select id from tags where slug='digital-and-creative'), ARRAY['digital']::lane[], ARRAY['luts','after effects','transitions']::text[], true, 24002),
  ('zines-and-comics', 'Zines & Comics', (select id from tags where slug='digital-and-creative'), ARRAY['maker','digital']::lane[], ARRAY['indie comic','digital zine']::text[], true, 24003),
  ('memberships-and-communities', 'Memberships & Communities', (select id from tags where slug='digital-and-creative'), ARRAY['digital']::lane[], ARRAY['patreon style','private community']::text[], true, 24004),
  ('music-and-audio', 'Music & Audio', (select id from tags where slug='digital-and-creative'), ARRAY['digital']::lane[], ARRAY['album','single','beats','stems']::text[], true, 24005),
  ('podcast-and-audio-series', 'Podcast & Audio Series', (select id from tags where slug='digital-and-creative'), ARRAY['digital']::lane[], ARRAY['podcast','audio show']::text[], true, 24006),
  ('software-and-apps', 'Software & Apps', (select id from tags where slug='digital-and-creative'), ARRAY['digital']::lane[], ARRAY['app','saas','plugin','tool']::text[], true, 24007),
  ('game-and-interactive', 'Game & Interactive', (select id from tags where slug='digital-and-creative'), ARRAY['digital']::lane[], ARRAY['indie game','game key','mod']::text[], true, 24008),
  ('digital-art-and-assets', 'Digital Art & Assets', (select id from tags where slug='digital-and-creative'), ARRAY['digital']::lane[], ARRAY['wallpaper','brushes','textures','3d assets']::text[], true, 24009),
  ('templates-and-presets', 'Templates & Presets', (select id from tags where slug='digital-and-creative'), ARRAY['digital']::lane[], ARRAY['lightroom presets','notion template','design template']::text[], true, 24010),
  ('fonts-and-type', 'Fonts & Type', (select id from tags where slug='digital-and-creative'), ARRAY['digital']::lane[], ARRAY['typeface','font family']::text[], true, 24011),
  ('courses-and-tutorials', 'Courses & Tutorials', (select id from tags where slug='digital-and-creative'), ARRAY['digital']::lane[], ARRAY['video course','tutorial series','workshop recording']::text[], true, 24012),
  ('ebooks-and-guides', 'Ebooks & Guides', (select id from tags where slug='digital-and-creative'), ARRAY['digital']::lane[], ARRAY['ebook','pdf guide','zine']::text[], true, 24013),
  ('stock-media', 'Stock Media', (select id from tags where slug='digital-and-creative'), ARRAY['digital']::lane[], ARRAY['stock photos','stock video','sound effects']::text[], true, 24014),
  ('practitioner-sessions', 'Practitioner Sessions', (select id from tags where slug='digital-and-creative'), ARRAY['digital']::lane[], ARRAY['1:1 session','coaching call','consultation']::text[], true, 24015),
  ('live-workshops', 'Live Workshops', (select id from tags where slug='digital-and-creative'), ARRAY['digital']::lane[], ARRAY['virtual workshop','live class','webinar']::text[], true, 24016),
  ('print-on-demand-art', 'Print on Demand Art', (select id from tags where slug='digital-and-creative'), ARRAY['maker','digital']::lane[], ARRAY['art print','poster print']::text[], true, 24017);
